### PR TITLE
[llvm] use new PassManager

### PR DESCRIPTION
**Pull request by mmarchini**
While working on #528 I decided to try to migrate our PassManager to the new version (we were using the legacy version before). We probably still need to make changes to `bpforc.h` since it assumes that we are using the legacy version. Also, if we decide to land this, we might lose support for older LLVM versions.

Tests will fail, as the IR generated by the new PassManager is incompatible with what we have on our codegen tests. Also, some programs are aborting, so we need to fix that before landing this.

Would love to get some reviews from folks familiar with LLVM.

### CODE REVIEW

**Comment by mmarchini** [comment]
FWIW, I think it would be better to migrate to the new PassManager before releasing 1.0, otherwise this migration should be treated as a major release.

**Comment by ajor** [comment]
Looks reasonable. What versions of LLVM does this work with?

**Comment by mmarchini** [comment]
I tested on LLVM 7 (I think). I'll test on other versions before marking this as ready for review.

**Comment by mmarchini** [comment]
Just took a quick look at this again. I'll try to get this working for 0.9.3 (not the next release).

**Pull request closed without merging**
