### PR TITLE
Add llvm 10 test

### PR DESCRIPTION
**Pull request by mmisono**

### CODE REVIEW

**Comment by mmisono** [comment]
This may conflict #1189.

**Comment by mmisono** [comment]
Should cache regex patterns. cf. #1192

**Comment by danobi** [comment]
Seems reasonable to me. What do you think @fbs?

**Comment by fbs** [comment]
Look OK :)

**Comment by mmisono** [comment]
I'll wait for #1189 before fixing regex patterns. It might eliminate differences in some test cases. Resolving conflicts (if any) will be easier also.

**Comment by fbs** [comment]
@mmisono  can you rebase this on amster?

**Comment by mmisono** [comment]
@fbs 
Is it OK to not wait for #1194? (not sure if it conflicts)

**Comment by fbs** [comment]
> @fbs
> Is it OK to not wait for #1194? (not sure if it conflicts)

I don't think it will conflict but if it does I can easily fix them.  Besides that one has no reviews yet and this one is mostly good to go.

**Comment by mmisono** [comment]
OK, rebased. Changes were little (only changed the type of `probe_read` in *.ll files).
I also updated the code so that it caches regex patterns.

**Pull request merged**
