### PR TITLE
Revert "Stop linking against bcc-loader-static"

### PR DESCRIPTION
**Pull request by ajor**
This reverts commit 5fbb7a7d634e75d0dbe01707705abadbfb90cac0.

#470 broke static builds

```
[ 34%] Linking CXX executable bpftrace
/usr/local/lib64/libbcc.a(usdt.cc.o): In function `USDT::Context::resolve_bin_path(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
usdt.cc:(.text+0x3b47): undefined reference to `bcc_procutils_which'
usdt.cc:(.text+0x3b8f): undefined reference to `bcc_procutils_which_so'
/usr/local/lib64/libbcc.a(usdt.cc.o): In function `USDT::Context::Context(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
usdt.cc:(.text+0x4a1f): undefined reference to `bcc_elf_foreach_usdt'
/usr/local/lib64/libbcc.a(usdt.cc.o): In function `USDT::Context::Context(int)':
usdt.cc:(.text+0x4b4f): undefined reference to `ProcStat::ProcStat(int)'
usdt.cc:(.text+0x4be5): undefined reference to `bcc_procutils_each_module'
/usr/local/lib64/libbcc.a(usdt.cc.o): In function `USDT::Context::Context(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
usdt.cc:(.text+0x4e04): undefined reference to `ProcStat::ProcStat(int)'
usdt.cc:(.text+0x4f10): undefined reference to `bcc_elf_foreach_usdt'
/usr/local/lib64/libbcc.a(usdt.cc.o): In function `USDT::Probe::in_shared_object(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
usdt.cc:(.text+0x5bd9): undefined reference to `bcc_elf_is_shared_obj'
/usr/local/lib64/libbcc.a(usdt.cc.o): In function `USDT::Probe::resolve_global_address(unsigned long*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long)':
usdt.cc:(.text+0x5ce9): undefined reference to `bcc_resolve_global_addr'
/usr/local/lib64/libbcc.a(usdt.cc.o): In function `USDT::Context::enable_probe(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
usdt.cc:(.text+0x6755): undefined reference to `ProcStat::is_stale()'
/usr/local/lib64/libbcc.a(usdt.cc.o): In function `USDT::Context::~Context()':
usdt.cc:(.text+0x6ce3): undefined reference to `ProcStat::is_stale()'
/usr/local/lib64/libbcc.a(usdt.cc.o): In function `USDT::Context::_each_module(char const*, unsigned long, unsigned long, unsigned long, bool, void*)':
usdt.cc:(.text+0x7d9c): undefined reference to `bcc_elf_foreach_usdt'
/usr/local/lib64/libbcc.a(usdt_args.cc.o): In function `USDT::Argument::get_global_address(unsigned long*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::experimental::optional<int> const&) const':
usdt_args.cc:(.text+0x2bf2): undefined reference to `ProcSyms::ProcSyms(int, bcc_symbol_option*)'
usdt_args.cc:(.text+0x2c03): undefined reference to `ProcSyms::resolve_name(char const*, char const*, unsigned long*)'
usdt_args.cc:(.text+0x2c12): undefined reference to `vtable for ProcSyms'
usdt_args.cc:(.text+0x2d68): undefined reference to `bcc_elf_is_shared_obj'
usdt_args.cc:(.text+0x2d85): undefined reference to `bcc_resolve_symname'
/usr/local/lib64/libbcc.a(usdt_args.cc.o): In function `ProcSyms::~ProcSyms()':
usdt_args.cc:(.text._ZN8ProcSymsD2Ev[_ZN8ProcSymsD5Ev]+0x5): undefined reference to `vtable for ProcSyms'
/usr/local/lib64/libbcc.a(usdt_args.cc.o): In function `ProcSyms::~ProcSyms()':
usdt_args.cc:(.text._ZN8ProcSymsD0Ev[_ZN8ProcSymsD5Ev]+0x5): undefined reference to `vtable for ProcSyms'
CMakeFiles/bpftrace.dir/attached_probe.cpp.o: In function `bpftrace::AttachedProbe::offset() const':
/home/travis/build/iovisor/bpftrace/src/attached_probe.cpp:206: undefined reference to `bcc_resolve_symname'
CMakeFiles/bpftrace.dir/bpftrace.cpp.o: In function `bpftrace::BPFtrace::~BPFtrace()':
/home/travis/build/iovisor/bpftrace/src/bpftrace.cpp:49: undefined reference to `bcc_free_symcache'
/home/travis/build/iovisor/bpftrace/src/bpftrace.cpp:53: undefined reference to `bcc_free_symcache'
CMakeFiles/bpftrace.dir/bpftrace.cpp.o: In function `bpftrace::BPFtrace::resolve_ksym[abi:cxx11](unsigned long, bool)':
/home/travis/build/iovisor/bpftrace/src/bpftrace.cpp:1493: undefined reference to `bcc_symcache_new'
/home/travis/build/iovisor/bpftrace/src/bpftrace.cpp:1495: undefined reference to `bcc_symcache_resolve'
CMakeFiles/bpftrace.dir/bpftrace.cpp.o: In function `bpftrace::BPFtrace::resolve_usym[abi:cxx11](unsigned long, int, bool, bool)':
/home/travis/build/iovisor/bpftrace/src/bpftrace.cpp:1607: undefined reference to `bcc_symcache_new'
/home/travis/build/iovisor/bpftrace/src/bpftrace.cpp:1615: undefined reference to `bcc_symcache_resolve'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/bpftrace.dir/build.make:388: src/bpftrace] Error 1
make[1]: *** [CMakeFiles/Makefile2:1133: src/CMakeFiles/bpftrace.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

### CODE REVIEW

**Comment by danobi** [comment]
Hmm that's weird. What's your environment (distro, installed bcc package)?

**Comment by ajor** [comment]
This is for the Alpine docker build - looking through the CI it started failing after that commit

**Comment by danobi** [comment]
Dang, I thought I saw the CI pass in the PR. Lemme dig into this a bit.

Also, what are your thoughts on consolidating the builds? It's quite difficult to maintain multiple ways to build.

**Comment by danobi** [comment]
Super weird; [this](https://github.com/iovisor/bcc/blob/master/src/cc/CMakeLists.txt#L108) would really make me think `libbcc-loader-static.a` is linked into `libbcc.a`.
```
$  ~/scratch/bcc/bcc-0.8.0/build/src/cc objdump --syms --demangle libbcc.a | grep bcc_symcache_resolve
$  ~/scratch/bcc/bcc-0.8.0/build/src/cc objdump --syms --demangle libbcc-loader-static.a | grep bcc_symcache_resolve 
00000000000003b0 g     F .text  000000000000001c bcc_symcache_resolve
00000000000003d0 g     F .text  0000000000000019 bcc_symcache_resolve_no_demangle
00000000000003f0 g     F .text  0000000000000017 bcc_symcache_resolve_name
```

Lemme ask Yonghong

**Comment by danobi** [comment]
Ok so it turns out the linker is probably discarding some symbols b/c nothing in bcc itself is using `bcc_symcache_resolve` (and friends). I'll go fix upstream bcc. In the meantime, reverting should be fine.

**Comment by ajor** [comment]
> Also, what are your thoughts on consolidating the builds? It's quite difficult to maintain multiple ways to build.

What did you have in mind? I do want to keep the static builds (even though I feel like half my development time last year went onto them!) as that's what I use on my computer and it makes it easier to get bpftrace onto a new machine

**Comment by mmarchini** [comment]
The biggest issue with static builds today is that we use alpine (because it's the only distro with `libclang.a`), and since alpine use musl we have legit crashes in some cases (#266), thus our static build tests on Travis are always red and we marked them as allow to fail, which makes it harder to know if a PR broke them.

If we can fix the musl issues and re-enable static builds it will (hopefully) be easier to keep it working. Alternatively, if we can get `libclang.a` into another distro (or even as part of LLVM Release files) we can migrate our static build from alpine to Ubuntu/CentOS/Fedora/etc.

**Comment by danobi** [comment]
@ajor I'm probably biased but I'm not a huge fan of the docker builds. More than that, though, it's kind of a pain to have to update two things at once when messing with the builds.

It's slower than root host (there's probably a way to make it faster but I am not enlightened enough) and if enough bpftrace developers abandon the non-docker build, it kind of leaves distro maintainers on a not very well-tested code path.

**Comment by ajor** [comment]
I'm not 100% committed to the docker builds, but do find them useful.

Definitely a lot slower which is a bit annoying, but the docker build should just be following the exact steps a distro maintainer (or anyone else) would need to do to build bpftrace on their own machine. Is this not the case? When do docker builds have to be dealt with differently to native builds? (I've not touched them in ages so can't really remember how it all fits together)

A benefit of them is that it forces us to keep an up-to-date list of dependencies which might get out of date in INSTALL.md.

**Comment by danobi** [comment]
Created https://github.com/iovisor/bcc/pull/2296

**Comment by danobi** [comment]
>  exact steps a distro maintainer (or anyone else) would need to do to build bpftrace on their own machine

Yeah I think the steps are the same, but the environment will be different. For example, most distros ship dynamically linked binaries. If we only ever test static builds, we can possibly miss issues.

> A benefit of them is that it forces us to keep an up-to-date list of dependencies which might get out of date in INSTALL.md.

Yeah I see that being valuable.

I guess after having not thought about this for a while, my opinion has softened. I'm ok with tabling it for now.

**Comment by mmarchini** [comment]
> If we only ever test static builds, we can possibly miss issues.

FWIW Travis tests both static and dynamic builds (but static builds are allowed to fail, since they have a lot of issues).

**Pull request merged**
