### PR TITLE
introduce perf formatting for ustack()/kstack()

### PR DESCRIPTION
**Pull request by mmarchini**
This will allow `ustack()` and `kstack()` to be used as follow:

`ustack()`: default stack limit, default formatting
`ustack(perf)`: default stack limit, Linux perf formatting
`ustack(16)`: stack limited to 16 frames, default formatting
`ustack(perf, 16)`: stack limited to 16 frames, Linux perf formatting

Default formatting looks like this:

```
Attaching 1 probe...

        lele+0
        __libc_start_main+231


        lele+0
        __libc_start_main+231
```

Linux perf formatting looks like this:

```
Attaching 1 probe...

	55e79dd4264a lele+0 (/home/mmarchini/lsls/main)
	7f92eda4bb97 __libc_start_main+231 (/lib/x86_64-linux-gnu/libc-2.27.so)


	55e79dd4264a lele+0 (/home/mmarchini/lsls/main)
	7f92eda4bb97 __libc_start_main+231 (/lib/x86_64-linux-gnu/libc-2.27.so)
```

It should be possible to add more formats in the future (for example, `folded`), as well as a custom string format.

### TODO before landing

  - [x] Refactor
  - [x] Update documentation
  - [x] Update tests

Ref.: #430

### CODE REVIEW

**Comment by brendangregg** [comment]
ready to merge?

**Comment by mmarchini** [comment]
Yes

**Comment by brendangregg** [comment]
thanks!

**Comment by jonhoo** [comment]
This format is still missing an [event line](https://github.com/brendangregg/FlameGraph/blob/1b1c6deede9c33c5134c920bdb7a44cc5528e9a7/stackcollapse-perf.pl#L203) to precede each stack trace. Is that something we might want to consider adding for compatibility with `perf script` output?

**Comment by brendangregg** [comment]
@jonhoo no, {ku}stack print stacks only. The event line can be printed with printf(). Plus the perf script event line format has changed across kernel versions, and probably will change again, so trying to support it is supporting a moving target.

**Comment by mmarchini** [comment]
I agree with @brendangregg. Besides, building the line with printf() gives us more flexibility to create custom flame graphs or other custom graphs/reports.

**Comment by jonhoo** [comment]
Makes sense. I wonder whether an example might serve users well though? Though I guess if the ultimate goal is `ustack(folded)`, then the event line becomes relatively less important (at least for flamegraph purposes).

**Comment by brendangregg** [comment]
I'm nervous about giving newbies a bpftrace script that does "perf script" output -- it'd be a lousy first impression for BPF. It'd be perf script, but worse (without the binary output efficiencies).

I want to get bpftrace emitting folded format (however we need to get it done) and show people that, since it's better than perf -- it uses in-kernel summaries. Afterwards we can show perf script output from bpftrace as a secondary option.

**Pull request merged**
