### PR TITLE
WIP Support building with clang toolchain

### PR DESCRIPTION
**Pull request by dalehamel**
Putting this up as a draft after seeing the discussion about a clang regression on #1088 and the corresponding patch in #1092 

I would also like to add this to github actions, and use a proper CMake "toolchain file" rather than hardcoding the binary names. 

FYI @fbs @mmisono

### CODE REVIEW

**Comment by dalehamel** [comment]
An alternative way to do this is have no special flag for Clang, and use the CMake `CMAKE_TOOLCHAIN_FILE` option, which I'm beginning to lean towards.

**Comment by dalehamel** [comment]
related to #1115 and #1093

**Comment by fbs** [comment]
Wouldn't doing something like `CC=/usr/bin/clang CXX=/usr/bin/clang++ cmake ..` be enough?

**Comment by dalehamel** [comment]
@fbs, it seems to not be quite that easy due to externalprojects not inheriting these always transparently. 

I’ve had more success by just forcing clang as the default system compiler and only using GCC tools if absolutely needed, but I was hoping to do this in cmake. In principal I think this is what a toolchain file is for.

**Pull request closed without merging**
