### PR TITLE
implicitly declare variables to 0 if used but not defined

### PR DESCRIPTION
**Pull request by mmarchini**
Preparing for https://github.com/iovisor/bpftrace/issues/53 (might also be used to refactor post-increment).

cc @brendangregg @dalehamel

### CODE REVIEW

**Comment by dalehamel** [comment]
I think this is a much cleaner approach with less duplication, as it will allow for ++ and -- to be incremented largely in the parser by just passing literals and using the same approach as you did for compound operations.

I'm not sure if there's a drawback to implicitly declaring *all* variables to 0, but it makes the behavior more consistent.

I'm in favor of this (but haven't tried it).

**Comment by brendangregg** [comment]
makes sense to me, thanks!

**Comment by ajor** [comment]
What's the use case for this? I thought it would probably be a mistake by the user if they use a variable before setting it. For maps this makes sense because they hold their values and their types get propagated backwards, but I'm not sure about doing this for variables.

I think the old error message was better for a program like this:
```
[alastair@arch build-debug]$ sudo ./src/bpftrace -e 'BEGIN { @y = $x; $x = "a" }'
Type mismatch for $x: trying to assign value of type 'string'
	when variable already contains a value of type 'integer
```

**Comment by ajor** [comment]
Oh, missed it was for the parser changes for `+=`
Still I wonder if there would be another way to go about this

**Comment by mmarchini** [comment]
IMO it's easier for the users if maps and variables have the same behavior regarding undeclared/implicitly declared variables. It makes the language simpler without affecting its versatility. 

> I think the old error message was better for a program like this

Agreed, maybe we can improve this scenario.

**Comment by ajor** [comment]
I'm not convinced about that, given that maps retain their values while variables don't. We don't actually allow undefined maps so this change makes maps and variables behave differently in that regard:

```
[alastair@arch src]$ sudo ./bpftrace -e 'BEGIN { printf("%d\n", @x) }'
Undefined map: @x
printf: %d specifier expects a value of type integer (none supplied)
```
```
[alastair@arch src]$ sudo ./bpftrace -e 'BEGIN { printf("%d\n", $x) }'
Attaching 1 probe...
0
^C
```



Is there a situation where someone would want variables to default to ints in their scripts?

**Comment by mmarchini** [comment]
> We don't actually allow undefined maps so this change makes maps and variables behave differently in that regard

The goal was to have them behave equally, but I missed this scenario. Thank you for pointing this out, I'll take a look to see how we can improve this situation.

**Pull request merged**
