### PR TITLE
Use host network when building docker image

### PR DESCRIPTION
**Pull request by danobi**
I was getting these errors before:
```
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.8/main: temporary error (try again later)
WARNING: Ignoring APKINDEX.adfa7ceb.tar.gz: No such file or directory
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.8/community: temporary error (try again later)
WARNING: Ignoring APKINDEX.efaa1f73.tar.gz: No such file or directory
ERROR: unsatisfiable constraints:
```

Adding this flag seemed to fix the issue.

### CODE REVIEW

**Comment by danobi** [comment]
I'm not very familiar with docker -- please let me know if this isn't the right fix.

**Comment by dalehamel** [comment]
that shouldn't be necessary, was this locally or in CI?

Sometimes DNS resolution screws up on my laptop when moving between work and office, docker mounts resolv.conf with a bind mount and it can act as a form of caching...

**Comment by fbs** [comment]
Should be ok to do this. You basically remove all network isolation (namespacing) with this, which we don't need for our builds. Might fix issues in edge cases where somone broke the docker0 bridge somehow.

Should probably update the other *build.sh too though.

**Comment by danobi** [comment]
> that shouldn't be necessary, was this locally or in CI?

This was locally on my laptop.

I'll update the other build.sh too.

**Pull request merged**
