### PR TITLE
Fix build on linux when using libc++

### PR DESCRIPTION
**Pull request by kraj**
##### Checklist

- [ ] Language changes are updated in `man/adoc/bpftrace.adoc` and if needed in `docs/reference_guide.md`
- [ ] User-visible and non-trivial changes updated in `CHANGELOG.md`
- [ ] The new behaviour is covered by tests

### CODE REVIEW

**Comment by fbs** [comment]
Thanks!

New LLVM version without breaking API changes? That is a first.

Can you fix the clang-format issue? :)

**Comment by kraj** [comment]
> Thanks!
> 
> New LLVM version without breaking API changes? That is a first.
> 

well not really see https://github.com/iovisor/bpftrace/issues/1963

> Can you fix the clang-format issue? :)

done

**Comment by fbs** [comment]
Ah in that case we shouldn't add LLVM13 to the supported LLVM list yet. The other fixes are ok tho:)

**Comment by kraj** [comment]
> Ah in that case we shouldn't add LLVM13 to the supported LLVM list yet. The other fixes are ok tho:)

ok done

**Review by danobi — APPROVED** [review]

**Pull request merged**
