### PR TITLE
RFC: Add xlock increase code for count function

### PR DESCRIPTION
**Pull request by olsajiri**
hi,
I tried the global data together with locking increase on count
function and it seems to be working. I think there're probably
other areas this could be put in.

The code still needs some testing/changes, but would be great
to get some input before I dive in more.

thanks,
jirka

---
Changing the count generation code to use eBPF global
data and locked increase to speedup the count function.

Having following code:

```
  # cat count.bt
  tracepoint:syscalls:sys_enter_write
  {
        @write = count();
  }

```
We generate following code even for single value increase:

```
   0: (b7) r1 = 0
   1: (7b) *(u64 *)(r10 -16) = r1
   2: (18) r1 = map[id:536]
   4: (bf) r2 = r10
   5: (07) r2 += -16
   6: (85) call htab_percpu_map_lookup_elem#100624
   7: (b7) r1 = 1
   8: (15) if r0 == 0x0 goto pc+2
   9: (79) r1 = *(u64 *)(r0 +0)
  10: (07) r1 += 1
  11: (7b) *(u64 *)(r10 -8) = r1
  12: (18) r1 = map[id:536]
  14: (bf) r2 = r10
  15: (07) r2 += -16
  16: (bf) r3 = r10
  17: (07) r3 += -8
  18: (b7) r4 = 0
  19: (85) call htab_percpu_map_update_elem#102848
  20: (b7) r0 = 0
  21: (95) exit
```
By adding the possibility to operate directly on the map's
data and locked increase we can use just this code:

```
   0: (18) r1 = map[id:542][0]+0
   2: (b7) r2 = 1
   3: (db) lock *(u64 *)(r1 +0) += r2
   4: (b7) r0 = 0
   5: (95) exit
```
This of course speeds up the processing, without bpftrace involved:

```
  # perf bench sched messaging -l 100000
  # Running 'sched/messaging' benchmark:
  # 20 sender and receiver processes per group
  # 10 groups == 400 processes run

       Total time: 58.194 [sec]
```

With current code:

```
  # bpftrace count.bt -c 'perf bench sched messaging -l 100000'
  Attaching 1 probe...
  # Running 'sched/messaging' benchmark:
  # 20 sender and receiver processes per group
  # 10 groups == 400 processes run

       Total time: 180.127 [sec]

  @write: 400000726
```

With change applied:

```
  # bpftrace count.bt -c 'perf bench sched messaging -l 100000'
  Attaching 1 probe...
  # Running 'sched/messaging' benchmark:
  # 20 sender and receiver processes per group
  # 10 groups == 400 processes run

       Total time: 62.975 [sec]

  @write: 400000492

```

### CODE REVIEW

**Comment by olsajiri** [comment]
I think this could be used for arrays where we know the number of elements like:

` bpftrace -e 'tracepoint:syscalls:sys_enter_* { @[probe] = count(); }'`

each probe would have offset into array data item so there'd be no need for lookup and update

**Comment by mmarchini** [comment]
Seems like the first commit shouldn't be in this PR?

**Comment by olsajiri** [comment]
It's there just to be in sync with my other changes,
but it got already merged, so I can rebase with master

However I just wanted to get some thoughts about the idea,
I also need to fix and add some tests.

**Comment by olsajiri** [comment]
right I just wanted to get some thoughts.. I'll polish the code and probably split
it to separate PRs.. like **global data/xlock stuff/elf option**  and send it out

thanks

**Pull request closed without merging**
