### PR TITLE
Increment variables and maps

### PR DESCRIPTION
**Pull request by dalehamel**
Initial pass for #412 to cover the immediate, highest value cases. A more complete implementation that also addresses #53 should replace this.

To accelerate implementation, variables and maps are handled separately which leads to a lot of code duplication. I believe that this can be simplified and refactored, but since the interface isn't going to change I think this is a reasonable "technical loan" to take. The proper implementation should probably just accept expressions in general, and then check if the expression is a variable or a map.

I'm missing codegen tests, I'm not sure how best to do those currently - any tips there?

In general, I'd appreciate a closer eye for the review of the codegen.

I added parser tests as well as basic usage docs to the reference guide.

### CODE REVIEW

**Comment by brendangregg** [comment]
Looks great, thanks!

```
bpftrace -e 'k:vfs_* { @a[probe]++; @b[probe] = count() }'
Attaching 54 probes...
^C

@a[kprobe:vfs_statx]: 2089
@a[kprobe:vfs_fsync_range]: 5
@a[kprobe:vfs_read]: 2885
@a[kprobe:vfs_getattr]: 5440
@a[kprobe:vfs_open]: 194
@a[kprobe:vfs_writev]: 658
@a[kprobe:vfs_write]: 1753
@a[kprobe:vfs_getattr_nosec]: 5439
@a[kprobe:vfs_statx_fd]: 40
@a[kprobe:vfs_lock_file]: 5
@a[kprobe:vfs_unlink]: 26


@b[kprobe:vfs_lock_file]: 5
@b[kprobe:vfs_fsync_range]: 5
@b[kprobe:vfs_unlink]: 26
@b[kprobe:vfs_statx_fd]: 40
@b[kprobe:vfs_open]: 194
@b[kprobe:vfs_writev]: 658
@b[kprobe:vfs_write]: 1756
@b[kprobe:vfs_statx]: 2089
@b[kprobe:vfs_read]: 2890
@b[kprobe:vfs_getattr_nosec]: 5439
@b[kprobe:vfs_getattr]: 5440
```

Is it easy to change the printed order to be ascending, like it is with count()? If that's difficult we can do it later as a follow up PR.

**Comment by dalehamel** [comment]
I’ll check how count does it, but offhand I’m guessing that should be something for a follow on PR.

**Comment by dalehamel** [comment]
@brendangregg actually it's a trivial patch to do this, but i'm not sure if there will be unintended consequences:

```diff

---
 src/bpftrace.cpp | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)

diff --git a/src/bpftrace.cpp b/src/bpftrace.cpp
index 7a35799..286bc14 100644
--- a/src/bpftrace.cpp
+++ b/src/bpftrace.cpp
@@ -825,7 +825,7 @@ int BPFtrace::print_map(IMap &map, uint32_t top, uint32_t div)
   {
     int value_size = map.type_.size;
     if (map.type_.type == Type::count || map.type_.type == Type::sum ||
-        map.type_.type == Type::min || map.type_.type == Type::max)
+        map.type_.type == Type::min || map.type_.type == Type::max || map.type_.type == Type::integer)
       value_size *= ncpus_;
     auto value = std::vector<uint8_t>(value_size);
     int err = bpf_lookup_elem(map.mapfd_, key.data(), value.data());
@@ -840,7 +840,7 @@ int BPFtrace::print_map(IMap &map, uint32_t top, uint32_t div)
     old_key = key;
   }

-  if (map.type_.type == Type::count || map.type_.type == Type::sum)
+  if (map.type_.type == Type::count || map.type_.type == Type::sum || map.type_.type == Type::integer)
   {
     std::sort(values_by_key.begin(), values_by_key.end(), [&](auto &a, auto &b)
     {
@@ -897,7 +897,7 @@ int BPFtrace::print_map(IMap &map, uint32_t top, uint32_t div)
       std::cout << resolve_uid(*(uint64_t*)(value.data())) << std::endl;
     else if (map.type_.type == Type::string)
       std::cout << value.data() << std::endl;
-    else if (map.type_.type == Type::count || map.type_.type == Type::sum)
+    else if (map.type_.type == Type::count || map.type_.type == Type::sum || map.type_.type == Type::integer)
       std::cout << reduce_value(value, ncpus_) / div << std::endl;
     else if (map.type_.type == Type::min)
       std::cout << min_value(value, ncpus_) / div << std::endl;
--
2.7.0

```

Basically since we aren't doing a `Call` here like we are with Count, we can't set it through the same mechanism (or at least I couldn't find a way to do so).

The workaround is to just set this behavior for all maps of integers, sort them by value, ascending. 

I think that's reasonable behavior, but there might be something i'm not thinking of.

I'll push this patch to the branch if you concur that it's probably safe.

**Comment by brendangregg** [comment]
I can't think of a problem. I haven't relied on the order of printing of integer maps.

**Comment by dalehamel** [comment]
Then I think this should be good to ship in my view. Thanks for the suggestion to add the sorting.

Should I file a new issue to cover fixes for this, and a better treatment of compound operators?

I think the codegen tests could also be pushed until that’s done as well.

**Comment by brendangregg** [comment]
Yes, I'd file a new issue for the follow up work. Thanks!

**Pull request merged**
