### PR TITLE
RFC: improved AST visiting/manipulation

### PR DESCRIPTION
**Pull request by fbs**
This fixes most of #1603, see that issue for some additional context.

The first two commits deduplicate the existing AST passes, instead of having to re-implement the tree traversing every time we can just inherit from a class that does that and call the parent function when needed. This doesn't do much for complex passes like semantic and codegen, but for simpler ones that don't touch all nodes (like tracepoint) it removes quite a bit of logic.

Then two cleanup commits, one to remove all the constructors without location info, as we use location everywhere we don't need those anymore. And one to dedupe the `accept()` function in every node, making it easier to modify if needed.

The next 5 are destructors for ast nodes based on #1055 and related test changes and the definition of copy constructors. All copies are shallow, settings all pointers to nullptr to avoid ownership issues. And hiding the copy constructor, forcing the use of the `clone()` method when needed to avoid accidental copies, which can corrupt the tree (due to the nullptr).

`AST: Implement custom dispatcher for node walking ` is the interesting part imo. Instead of using double dispatch it implements a custom dispatcher which  makes it eaiser to use custom return types and to write callback functions. The commit message has all the details.

The last two rewrite the CallbackVisitor to the new ASTNodeVisitor class and a basic implementation of a postional parameter removing class, which should simplify the semantic phase.

----

The whole things is quite big, a lot of test refactoring and things that add to the total lines. When/if we decide to merge this I'll split it into parts to make it a bit easier.

Opening this as RFC to get some feedback on the idea itself, i.e. the new dispatching and the idea of adding more/simpler passes.

### CODE REVIEW

**Comment by mmisono** [comment]
Just skimmed through the commits, but implementing CallbackVisitor was a bit of pain, so the new one looks nice.

**Comment by fbs** [comment]
I've fixed some bugs and rebased it. 

The positional param pass should be mostly done now. The unit tests are broken ofcourse but it passes the runtime test suite. Some stuff is still missing but it should be good enough to show the concept.

**Comment by fbs** [comment]
@danobi how do you feel about this one? I want to do some tests to see if i can get the dispatch overhead down a bit but I don't think it is an issue for the amount of passes we will have anyway.

**Review by danobi — COMMENTED** [review]
I like the new API. I'm a little concerned about the complexity of the internals but I think I understand it. I think it'd also be worth writing some short docs on how to extend the API and why things are designed the way they are. Maybe inline where `NodeDispatcher` is defined.

**Comment by fbs** [comment]
> I like the new API. I'm a little concerned about the complexity of the internals but I think I understand it. I think it'd also be worth writing some short docs on how to extend the API and why things are designed the way they are. Maybe inline where `NodeDispatcher` is defined.

Yeah I'll add some inline comments and things to make it a bit easier to follow.

Thanks

**Comment by fbs** [comment]
After messing with it a bit more I think its best to keep both versions. Double dispatch is faster and if we dispatch trough `Visit()` instead of calling `node->accept()` directly we also get the generic node to dispatch through.

For mutators we  can keep the vtable based dispatch, its a bit trickier and higher overhead but more flexible.

I've also added a basic pass manager. The idea is that every pass adds a function that indicates how to run the pass. This will make it easier to do diagnostics between passes (e.g. print ast, print time it took) and should simplify main. All config is stored in a PassCtx object, its a bit ugly but works for now.  Too many options in there indicates that we have to many special passes.

Hope to get it finished in the next few days.

**Comment by fbs** [comment]
#1655 does most of this. The posparam transformer will be part of a follow up once that one lands

**Pull request closed without merging**
