### PR TITLE
Rebase of #280 with merge conflicts resolved

### PR DESCRIPTION
**Pull request by mmarchini**

### CODE REVIEW

**Comment by dalehamel** [comment]
@mmarchini related to my comment in https://github.com/iovisor/bpftrace/pull/280#issuecomment-467057600, I tried a simpler version to see if it's just me.

I can't get the following example to work:

```
ruby -e 'def test; puts "test"; end; while true; test; sleep 1; end'
```

And, in another terminal:
```
bpftrace -e 'usdt::method__entry { printf("here\n") }' -p ${RUBY_PID}
```

However, nothing prints, where I would expect this to happen every second... so something fishy is going on here.

In my case, the ruby process is inside a container. I'm not sure if that makes a difference. The ruby i'm using is indeed built with dtrace probes. Do you have a case working where you've been able to attach probes successfully? How about inside of a container?

**Comment by mmarchini** [comment]
@dalehamel is it also happening on `master`?

**Comment by dalehamel** [comment]
@mmarchini I can't easily compare to master, as I'm relying on the path handling introduced in this PR. I was not able to get anything working against master either (where I specified the path relative to /proc/PID/root) in various previous attempts, but I'll attempt to see if i can get anything working there, and I'll also try and get an example with `ucalls` or something similar from bcc for comparison.

**Comment by mmarchini** [comment]
I'll try to run something inside a container to see what happens.

**Comment by dalehamel** [comment]
I compiled the `tracetest` example from https://www.joyfulbikeshedding.com/blog/2019-01-31-full-system-dynamic-tracing-on-linux-using-ebpf-and-bpftrace.html#usdt-probe-example and i was able to get it working inside of a container without issues.

This might be specific to the ruby dtrace probes i'm trying to use.

**Comment by mmarchini** [comment]
Can you share the output of `readelf --notes /path/to/ruby`? It might be some weird formatting in the probes description.

**Comment by dalehamel** [comment]
yup, here it is: https://gist.github.com/dalehamel/7a8b9dacc68c653fdacfa54a856f14b2

**Comment by dalehamel** [comment]
BTW, thanks for the debugging suggestions, but I think that this is unrelated to the PR / your rebase. I can follow up with a separate issue.

**Comment by mmarchini** [comment]
I think we should land this (or #280) sooner than later, to avoid another merge conflict.

**Comment by dalehamel** [comment]
I agree, it would be nice to get @tjfontaine to sign off, but I think the work here is done and attribution of the original authorship is preserved in the commits.

The code seems functional and does what is expected in my testing of it.

Every has busy spells once in a while

**Comment by mmarchini** [comment]
Just have to fix the failing test first (which might actually be a legitimate failure?)

**Comment by mmarchini** [comment]
CI should be green now. @brendangregg @tjfontaine can we move this forward?

**Comment by brendangregg** [comment]
merging, thanks everyone!

**Pull request merged**
