### PR TITLE
Add 'cat' builtin (#543)

### PR DESCRIPTION
**Pull request by caringi**

### CODE REVIEW

**Comment by brendangregg** [comment]
Looks great, thanks!

I was wondering about sanitizing the pathname and removing ";" and other characters, otherwise `cat("/etc/motd; date")` etc would work, but I think that may already be handled by this:

```
  std::ifstream file(filename);
  std::string line;

  if (file.fail())
```

If that just does a path lookup, then it'll fail there, so we don't need extra sanitizing.

This doesn't matter much anyway, since bpftrace can only be used by root, and you can run anything in `system()`. I'm thinking more about typos and confusing people.

**Comment by ajor** [comment]
Could you add it to the `builtin_functions` semantic analyser test and also add a new semantic analyser test checking it's arguments please?

**Comment by caringi** [comment]
@brendangregg I think an extra sanitization here is not needed, if something like `cat("/etc/motd; date")` is used, the result is just: `ERROR: file not found: /proc/loadavg; date` when the probe is fired. Another idea would be to finish execution if a file which doesn't exist is passed. I'm up to you...

@ajor done. :)

**Comment by brendangregg** [comment]
Looks like the build failures are unrelated, so merging. Thanks!

**Pull request merged**
