### PR TITLE
Add location info into AST

### PR DESCRIPTION
**Pull request by fbs**
This adds location support into all relevant parts of the AST. Which hopefully makes it easier to start using this feature throughout the code base, as you won't have to update the AST and parser anymore. 
There might be a few bugs in it, passing either too much or too little location info, but those should be easy to fix if they pop up. They're hard to spot now as not everything is using the location info yet but I think most of them are correct.

I've also updated the error prints of calls, builtins, strings and identifiers, which now look like:

```
stdin:1:31-37: ERROR: The retval builtin can only be used with 'kretprobe' and 'uretprobe' probes (try to use args->ret instead)
t:syscalls:sys_enter_openat { retval ; arg0 ; call(); lhist(1); join(1,2,3,4,5); uaddr("a.z"); @a = hist(); a }
                              ~~~~~~
stdin:1:40-44: ERROR: The arg0 builtin can only be used with 'kprobes', 'uprobes' and 'usdt' probes
t:syscalls:sys_enter_openat { retval ; arg0 ; call(); lhist(1); join(1,2,3,4,5); uaddr("a.z"); @a = hist(); a }
                                       ~~~~
stdin:1:47-53: ERROR: Unknown function: 'call'
t:syscalls:sys_enter_openat { retval ; arg0 ; call(); lhist(1); join(1,2,3,4,5); uaddr("a.z"); @a = hist(); a }
                                              ~~~~~~
stdin:1:55-63: ERROR: lhist() should be assigned to a map
t:syscalls:sys_enter_openat { retval ; arg0 ; call(); lhist(1); join(1,2,3,4,5); uaddr("a.z"); @a = hist(); a }
                                                      ~~~~~~~~
stdin:1:55-63: ERROR: lhist() requires 4 arguments (1 provided)
t:syscalls:sys_enter_openat { retval ; arg0 ; call(); lhist(1); join(1,2,3,4,5); uaddr("a.z"); @a = hist(); a }
                                                      ~~~~~~~~
stdin:1:65-80: ERROR: join() takes up to 2 arguments (5 provided)
t:syscalls:sys_enter_openat { retval ; arg0 ; call(); lhist(1); join(1,2,3,4,5); uaddr("a.z"); @a = hist(); a }
                                                                ~~~~~~~~~~~~~~~
stdin:1:101-107: ERROR: hist() requires one argument (0 provided)
t:syscalls:sys_enter_openat { retval ; arg0 ; call(); lhist(1); join(1,2,3,4,5); uaddr("a.z"); @a = hist(); a }
                                                                                                    ~~~~~~
stdin:1:109-110: ERROR: Unknown identifier: 'a'
t:syscalls:sys_enter_openat { retval ; arg0 ; call(); lhist(1); join(1,2,3,4,5); uaddr("a.z"); @a = hist(); a }
                                                                                                            ~
```

### CODE REVIEW

**Comment by javierhonduco** [comment]
Haven't done proper review yet, but this is beautiful 😄

**Comment by mmarchini** [comment]
Should we remove constructors without location information from `ast.h` in the future?

**Comment by fbs** [comment]
> Should we remove constructors without location information from `ast.h` in the future?

Probably, that way we cannot accidentally forget to pass location info when extending the parser. If you really don't want a location you can always in the default empty location.

I'll look into it :)

**Comment by mmarchini** [comment]
Good, I'll open an issue for that (don't need to do it in this PR, we can first merge it and remove the other contractors later).

**Comment by fbs** [comment]
> don't need to do it in this PR

It will probably take a few more MRs before this is fully implemented throughout the codebase (and tested). Once that is done I'll look into cleaning up

**Pull request merged**
