### PR TITLE
Libbpf note that btf__get_nr_types() == btf__type_cnt() - 1.

### PR DESCRIPTION
**Pull request by Rtoax**
See also: https://github.com/libbpf/libbpf/blob/master/src/btf.h#L135

### CODE REVIEW

**Comment by viktormalik** [comment]
I'm wondering what's the proper way of indexing through BTF types now. It was `1 <= i <= btf__get_nr_types()`, does it still start with 1 after this change?

**Comment by Rtoax** [comment]
> I'm wondering what's the proper way of indexing through BTF types now. It was `1 <= i <= btf__get_nr_types()`, does it still start with 1 after this change?

in https://github.com/libbpf/libbpf/blob/master/src/btf.c#L441, `btf__get_nr_types = btf__type_cnt - 1`, whether `1 <= i <= btf__get_nr_types()` is start with 1 or not

```c
__u32 btf__get_nr_types(const struct btf *btf)
{
	return btf->start_id + btf->nr_types - 1;
}

__u32 btf__type_cnt(const struct btf *btf)
{
	return btf->start_id + btf->nr_types;
}
```

**Comment by viktormalik** [comment]
Ok, it still seems to start with 1, so we don't need to change anything else.

**Review by viktormalik — APPROVED** [review]

**Comment by danobi** [comment]
Looking at https://github.com/libbpf/libbpf/commit/596c9a2d771683889c8c4989acebece0f8e94416, this change seems right to me

**Review by danobi — APPROVED** [review]

**Pull request merged**
