### PR TITLE
[tests] run bpftrace -d on tools to make sure we can parse end codege…

### PR DESCRIPTION
**Pull request by mmarchini**
…n them

### CODE REVIEW

**Comment by ajor** [comment]
Looks good!

**Comment by mmarchini** [comment]
Ok, so it seems like we have a similar problem to runtime tests here (features and tracepoints not available on 4.4). I might break this into smaller pull requests since it introduces a few other things as well, and keep those tests disabled on Travis for now.

**Comment by mmarchini** [comment]
List of tools we can't test on 4.4:

  - `execsnoop.bt`: missing tracepoint syscalls:sys_enter_execve
  - `mdflush.bt`: missing field on struct
  - `oomkill.bt`: missing fields on struct
  - `statsnoop.bt`: missing tracepoint syscalls:sys_enter_statx

**Comment by mmarchini** [comment]
Superseded by #568 and #570

**Pull request closed without merging**
