### PR TITLE
usdt,uprobe: resolve binary name from PATH

### PR DESCRIPTION
**Pull request by mmarchini**

### CODE REVIEW

**Comment by mmarchini** [comment]
@danobi any special reason to use `command -pv ` instead of `which ` on #303? `command -pv ` didn't worked here to resolve `node` when using [nvm](https://github.com/creationix/nvm).

**Comment by danobi** [comment]
@mmarchini yeah this was the reason: https://github.com/koalaman/shellcheck/wiki/SC2230 .

On the nvm README, there seems to be a note about it:
```
Note: On Linux, after running the install script, if you get nvm: command not found or see no feedback from your terminal after you type:

command -v nvm

simply close your current terminal, open a new terminal, and try verifying again.
```

**Comment by mmarchini** [comment]
`command -v node` works, `command -pv node` doesn't 🤔

Can we use `command -v` instead?

**Comment by danobi** [comment]
Yeah. Hmm I wonder why I added `-p`. Reading through the man page, it seems we would want the user's PATH and not just the default.

**Comment by brendangregg** [comment]
Thanks; although has conflicts now I merged the other one (at long last).

library path next? should be able to do u:libc:strlen or u:c:strlen (bcc's trace has a syntax like the latter where the "lib" is dropped, but I think I'd prefer to see it, so u:libc:strlen).

**Pull request merged**
