### PR TITLE
Usdt specify provider ns

### PR DESCRIPTION
**Pull request by dalehamel**
Fixes for #328 

This should allow for manually specifying a USDT probe's provider namespace.

I've also added:

- [x] Documentation for the behavior
- [x] Parser and semantic tests

I've manually done a functional test against the example from https://www.joyfulbikeshedding.com/blog/2019-01-31-full-system-dynamic-tracing-on-linux-using-ebpf-and-bpftrace.html#usdt-probe-example, in which @foobarwidget mentions this issue and confirmed that this works as expected.

This will probably cause conflicts with #280 as they touch a lot of the same code.

@brendangregg @mmarchini :eyes: please, since you were in the issue conversation.

### CODE REVIEW

**Comment by dalehamel** [comment]
I just had a thought that `GetProviderFromPath` could probably also be made to be a bit smarter.

Eg, it seems reasonable to always chop off a filename suffix. So `libc.so` should reasonably be inferred to be `/lib/libc`. It might also make sense to split on `-` and take the first token as well, in which case `/lib/libc-2.27.so` would also become `libc`, which would solve a lot of issues where the namespace name can be reasonably pulled from the path with just a bit more parsing sauce.

I can't think of *any* libraries that include a `-` in their base name, but this could be a problem for binaries, where naming is more unpredictable.

**Comment by tjfontaine** [comment]
`GetProviderFromPath` is a very rudimentary/naive solution, and probably should be scrapped. The reality is that the provider name is customizable, and with things like `libstapsdt` (and before it was `libusdt`) during runtime multiple providers may be instantiated independently of what was included in the binary during compilation.

I think there's also an impedance mismatch between the 4 tuple that `dtrace` uses, and the tuple that `bpftrace` uses, that makes specifying provider for `usdt` a bit complicated.

Also, at the end of the day, regardless of setting the `provider` here in `bpftrace` we have a larger problem where `bcc` can't enable probes of the same name with different providers -- https://github.com/iovisor/bcc/blob/master/src/cc/usdt/usdt.cc#L299 which is probably more common that people realize. So this plumbing for the dispatch of providers and probes goes all the way down.

**Comment by dalehamel** [comment]
> we have a larger problem where `bcc` can't enable probes of the same name with different providers

Yes I noticed that code in bcc while doing some related debugging. I agree with your assessment that this should be propagated all the way through.

> I think there's also an impedance mismatch between the 4 tuple that `dtrace` uses, and the tuple that `bpftrace` uses, that makes specifying provider for `usdt` a bit complicated.

Can you elaborate?

**Comment by brendangregg** [comment]
Thanks @tjfontaine, we should get that bcc limitation fixed. 

Thanks @dalehamel -- I think this looks good. Any reason not to merge right now? It might add some extra merge changes to #280.

**Comment by dalehamel** [comment]
@brendangregg if you're asking me, I think it should be good to merge if you agree the approach is sound.

There are two things I'm a bit worried about, but I think are both unavoidable:
* That I had to add 4 lines to the parser (to cover all combinations of `wildcard` and `string`), when I was originally expecting to add just one. I don't see a way around that though, in order for this to be consistent with the semantics of other attach points. Otherwise, it wouldn't follow conventions of other attach_points accepting string parameters in both their quoted and unquoted form.
* Also related to the parser, the way that tuples are handled presently means that the 3rd parameter of any 4-tuple in the future will always be assumed to be "provider namespace" in the present implementation. If we start having cases where other probes would use 4-tuples, then this could be an issue. This isn't a problem yet though, and I think it should be easy enough to make the semantic-analyzer more flexible for future cases as is already done for 3-tuples.

And to clarify, I just wanted to give a courtesy heads-up that it might complicate @tjfontaine's rebase in #280 (and I'm also pretty excited for some of the changes in there), but I don't think this should block on that. If this is merged first it should be easy enough to rebase #280 on top of it, even though it will definitely introduce a few conflicts.

**Comment by brendangregg** [comment]
Ok, I'll merge, thanks. Sorry for the pain @tjfontaine, we all still want your PR!

**Pull request merged**
