### PR TITLE
New join behavior

### PR DESCRIPTION
**Pull request by mmarchini**
Built on top of #750.

This is still a work-in-progress. Tests were not updated and not all cases are working, but I decided to open the PR already because there are some issues we need to consider before moving forward.

Below are some considerations for each scenario I tested. tl;dr I'm not sure it's a good idea to change how join works, due to it's nature.

## Pass `join` to `printf`

This is the most trivial use case for the new behavior, and it's working:

```
# bpftrace -e 'tracepoint:syscalls:sys_enter_execve { printf("%s\n", join(args->argv)) }'
Attaching 1 probe...
ls --color=tty
ps1_exec_async
tmux-set-left-statusbar
git config --get oh-my-zsh.hide-status
...
```

## Assign `join` to map

```
# bpftrace -ve 'tracepoint:syscalls:sys_enter_execve { @ = join(args->argv) }'
Attaching 1 probe...

Error log: 
0: (bf) r3 = r1
1: (07) r3 += 24
2: (bf) r1 = r10
3: (07) r1 += -8
4: (b7) r2 = 8
5: (85) call bpf_probe_read#4
6: (79) r7 = *(u64 *)(r10 -8)
7: (18) r1 = 0xffff890e70ae5800
9: (b7) r8 = 0
10: (63) *(u32 *)(r10 -12) = r8
11: (bf) r2 = r10
12: (07) r2 += -12
13: (85) call bpf_map_lookup_elem#1
14: (bf) r6 = r0
15: (55) if r6 != 0x0 goto pc+2
 R0=inv0 R6=inv0 R7=inv(id=0) R8=inv0 R10=fp0
16: (b7) r0 = 0
17: (95) exit

from 15 to 18: R0=map_value(id=0,off=0,ks=4,vs=16392,imm=0) R6=map_value(id=0,off=0,ks=4,vs=16392,imm=0) R7=inv(id=0) R8=inv0 R10=fp0
18: (7b) *(u64 *)(r6 +0) = r8
 R0=map_value(id=0,off=0,ks=4,vs=16392,imm=0) R6=map_value(id=0,off=0,ks=4,vs=16392,imm=0) R7=inv(id=0) R8=inv0 R10=fp0
19: (bf) r1 = r10
20: (07) r1 += -8
21: (b7) r2 = 8
22: (bf) r3 = r7
23: (85) call bpf_probe_read#4
24: (65) if r0 s> 0xffffffff goto pc+11
 R0=inv(id=0,umin_value=9223372036854775808,var_off=(0x8000000000000000; 0x7fffffffffffffff)) R6=map_value(id=0,off=0,ks=4,vs=16392,imm=0) R7=inv(id=0) R8=inv0 R10=fp0
25: (b7) r1 = 0
26: (7b) *(u64 *)(r10 -8) = r1
27: (18) r1 = 0xffff890e70ae4d00
29: (bf) r2 = r10
30: (07) r2 += -8
31: (bf) r3 = r6
32: (b7) r4 = 0
33: (85) call bpf_map_update_elem#2
R3 type=map_value expected=fp

Error loading program: tracepoint:syscalls:sys_enter_execve
```

This doesn't work because `BPF_map_update_elem` doesn't accept a map address as it's third (`void *value`) argument, but storing the `join` in the stack is not feasible since it will blow the stack immediately (join size is  `8 + 16 * 1024`). We `could` keep each join call in a separate map and store this joinmap key on our map when assigning (similar to how getstackid works), but I'm still thinking if this is a good idea.

## Use `join` as map key

```
# bpftrace -ve 'tracepoint:syscalls:sys_enter_execve { @[join(args->argv)] = 0; }'
Error creating map: '@'
error: <unknown>:0:0: in function tracepoint:syscalls:sys_enter_execve i64 (i8*): Looks like the BPF stack limit of 512 bytes is exceeded. Please move large on stack variables into BPF per-cpu array map.

```

Besides having the same problem as described above (map_lookup_elem doesn't accept a map as it's key), there are memset and memcpy instructions in the code path of getMapKey, which means we'll either blow the stack, or get a `invalid call to builtin method` if LLVM doesn't unroll these calls.

## Assign `join` to variable, use on printf

```
# bpftrace -ve 'tracepoint:syscalls:sys_enter_execve { $a = join(args->argv); printf("%s\n", $a)}'
error: <unknown>:0:0: in function tracepoint:syscalls:sys_enter_execve i64 (i8*): A call to built-in function 'memset' is not supported.
```

Since variables are stored on the stack, and the size of join is huge, it will blow the stack, or we'll get the error above if LLVM doesn't unroll memset/memcpy.

-----

`join` is an memory expensive operation, which causes most of the problems described above. We could make some improvements (do the join in BPF scope, save it as string, limit it's size like we do with str, etc.), but the way join works today is probably better than what we could achieve by making join usable as a map key/printf arg/map value. Not sure what others think, but maybe we should keep join as it is.

### CODE REVIEW

**Comment by brendangregg** [comment]
Just to connect the dots: this would fix #26 (if this is ever merged).

**Comment by tyroguru** [comment]
@mmarchini - thanks for all the great work you're doing in general but on the join issue as in this case. It seems that bpf's inherent limit with the way variables are stored on the stack is a major pain for this. I'm generally against specialising individual functions/builtins to accommodate a particular operation like this (printf/join as in this case) as it seems like a recipe for maintenance issues down the line. 

I think that the solution of assigning the result of join() to a variable and typing it as a string is the only one that seems correct (as then you could do whatever you pleased with it). Everything else seems a bit like putting lipstick on a pig.

**Comment by mmarchini** [comment]
@tyroguru thank you for the feedback.

> I'm generally against specialising individual functions/builtins to accommodate a particular operation like this (printf/join as in this case) as it seems like a recipe for maintenance issues down the line.

Sorry, I think my PR description was not clear. With this implementation there is not special case between printf/join.

As for:

> I think that the solution of assigning the result of join() to a variable and typing it as a string is the only one that seems correct

We still have the problem that saving the result of `join` to a variable will blow the stack in most cases (unless the program is extremely simple).

Overall I think this should not be implemented in the near future due to BPF limitations. We might want to revisit it in the future (if `BPF_map_update_elem` is changed to accept a map address as well and/or when we have bounded loops generally available in BPF). But if anyone has suggestions to fix the issues outlined here I would be happy to hear and discuss further.

**Comment by mmarchini** [comment]
I'm closing this PR as I don't intend to work on this again in the near future. I'll keep the issue open since it would be feasible to implement this after some kernel changes (and one of those changes is already upstream).

If anyone want to take over, feel free to do so.

**Pull request closed without merging**
