### PR TITLE
Runtime test suite

### PR DESCRIPTION
**Pull request by williangaspar**
I Decided to make a second PR, the first one is a little bit cloudy.

### CODE REVIEW

**Comment by brendangregg** [comment]
Thanks, I think this is really nice. I like how the text files focus on just the tests: should be easy to maintain and add tests to.

```
NAME username
RUN bpftrace -e 'i:ms:1 { printf("SUCCESS '$test' %s\n", username); exit(); }'
EXPECT SUCCESS username .*
TIMEOUT 5

NAME probe
RUN bpftrace -e 'k:do_nanosleep { printf("SUCCESS '$test' %s\n", probe); exit(); }'
EXPECT SUCCESS probe kprobe:do_nanosleep
TIMEOUT 5
BEFORE sleep 1 && sleep 1 &

NAME curtask
RUN bpftrace -e 'i:ms:1 { printf("SUCCESS '$test' %d\n", curtask); exit(); }'
EXPECT SUCCESS curtask -?[0-9][0-9]*
TIMEOUT 5
```

:-)

**Comment by brendangregg** [comment]
I like it. I tested and had 7 failures out of 62 tests, and I've debugged why and have the suggested fixes below for 4 of them. If you can get them fixed, I'll merge this and we can chase down the remaining 3 later (one of which I think is just a kernel version difference).

Here's the failures on my machine:

```
join ERROR
	Expected: echo A
	Found: Attaching 2 probes...

A

A


str ERROR
	Expected: P: /bin/sh
	Found: Attaching 2 probes...

10

10

10


sym ERROR
	Expected: P: /bin/sh
	Found: Attaching 1 probe...

global_associative_arrays ERROR
	Expected: @start\[[0-9]*\]\:\s[0-9]*
	Found: 


cgroup ERROR
	Expected: SUCCESS cgroup -?[0-9][0-9]*
	Found: Attaching 1 probe...

Error loading program: interval:ms:1 (try -v)


uprobe  TIMEOUT 
uretprobe  TIMEOUT 
```

### join

Suggested fix:

```
EXPECT A
```

### str

I don't know what's up there. I'm on 4.15 x86_64, and it's printing arg1 not arg0. Maybe sys_execve() changed on this kernel version?

### sym

Possible regression. This works:

```
sudo ./src/bpftrace -e 'kprobe:do_nanosleep { @[reg("ip"), sym(reg("ip"))] = count(); }'
Attaching 1 probe...
^C

@[-1160134639, do_nanosleep]: 215
```

But this doesn't:

```
sudo ./src/bpftrace -e 'kprobe:do_nanosleep { printf("got: %llx %s\n", reg("ip"), sym(reg("ip"))); exit();}'
Attaching 1 probe...
got: ffffffffbad9c011 
```

### global_associative_arrays

Suggested fix:

```
NAME global_associative_arrays
RUN bpftrace -e 'k:do_nanosleep { @start[tid] = nsecs; } kretprobe:do_nanosleep /@start[tid] != 0/ { printf("slept for %d ms\n", (nsecs - @start[tid]) / 1000000); delete(@start[tid]); exit();}'
EXPECT slept for [0-9]+ ms
TIMEOUT 5
BEFORE (sleep 1; sleep 1) &
```

I think I fixed the intent of the BEFORE command as well: it schedules a "sleep 1" that should run while tracing (unless another sleep happened in the meantime).

### cgroups

I think my kernel version is just too old for this BPF function, so ignore this failure for now.

```# sudo ./src/bpftrace -v -e 'i:ms:1 { printf("SUCCESS '$test' %d\n", cgroup); exit(); }' 
Attaching 1 probe...

Error log: 
0: (bf) r6 = r1
1: (b7) r1 = 0
2: (7b) *(u64 *)(r10 -16) = r1
3: (85) call unknown#80
invalid func unknown#80

Error loading program: interval:ms:1
```

### uprobe & uretprobe

These expect some bash readline()s, but that won't happen unless someone is interactive.

Suggested fix:

```
NAME uprobe
RUN bpftrace -e 'uprobe:/bin/bash:echo_builtin { printf("arg0: %d", arg0); exit();}'
EXPECT arg0: [0-9]*
TIMEOUT 5
BEFORE (sleep 1; /bin/bash -c echo) &

NAME uretprobe
RUN bpftrace -e 'uretprobe:/bin/bash:echo_builtin { printf("readline: %d\n", retval); exit();}'
EXPECT readline: [0-9]*
TIMEOUT 5
BEFORE (sleep 1; /bin/bash -c echo) &
```

**Comment by williangaspar** [comment]
I think I need to add some tests for BEGIN and END

**Comment by brendangregg** [comment]
We can close this, right, since we merged the other one?

**Comment by mmarchini** [comment]
> We can close this, right, since we merged the other one?

#226 was closed in favor of this Pull Request. Or do you mean another PR?

**Comment by brendangregg** [comment]
Oh, I was confused. Are we ready to merge this one?

**Comment by mmarchini** [comment]
Code-wise I think this can be merged (we can make further improvements in follow-up PRs), but I would like to see this running on Travis before merging it (right now only unit tests are running there).

**Comment by brendangregg** [comment]
Wouldn't it be easier to merge first, then setup Travis after?

**Comment by mmarchini** [comment]
Tests are passing on CI with those latest changes. Merging...

**Pull request merged**
