### PR TITLE
cmake: add BUILD_TESTING support

### PR DESCRIPTION
**Pull request by cyphar**
Currently tests/ requires pulling gtest from git, which is far from
ideal for distribution builds (not to mention we don't need to unit test
in an RPM build). So add the ability to disable tests/ builds.

Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>

### CODE REVIEW

**Comment by cyphar** [comment]
This is an extension of #327 and #227.

**Comment by cyphar** [comment]
Also, it'd be great if we could get a new release which includes both this and #327 (so distributions can use a versioned build).

**Comment by cyphar** [comment]
Tests are still built by default, and you can disabled them with `-DBUILD_TESTING=OFF`. [CTest is documented here.](https://cmake.org/cmake/help/v3.7/module/CTest.html)

I don't mind waiting 2-3 weeks, so long as there's a release coming at some point in the future so I can stop building the openSUSE packages off `master`. :P

**Comment by brendangregg** [comment]
ok thanks, yes, we're not far off 0.9.

**Pull request merged**
