### PR TITLE
Enable build warnings

### LINKED ISSUE #316: Build warnings are turned off
While doing some packaging, I discovered the cmake build has all the build warnings turned off: https://github.com/iovisor/bpftrace/blob/master/CMakeLists.txt#L8-L21 . Any reason for this? Can I turn them back on?

It catches a couple of harmless issues right now. However, we might get lucky in the future and have it catch some trickier bugs.

### PR DESCRIPTION
**Pull request by sourabhtk37**
Closes #316 
Signed-off-by: T K Sourab <sourabhtk37@gmail.com>

### CODE REVIEW

**Comment by paulmenzel** [comment]
Looks good. I’d use imperative mood though: Enable ….

Maybe comment, if warnings are shown now.

**Comment by sourabhtk37** [comment]
Yup, warnings are shown.

**Comment by brendangregg** [comment]
Uh, wow. With this, I get about 200 pages of warnings. We'll want to fix these. Even if they aren't a technical problem, it's going to alarm newcomers when they do a build.

Plus, if we merge this, I imagine it make cause some automated build systems to fail -- which are expecting no warnings/errors.

Anyone want to make a start on fixing them before we expose them like this?

**Comment by brendangregg** [comment]
I just merged #396 so we are a step closer to warning-free builds.

**Comment by sourabhtk37** [comment]
Closing this PR.

**Pull request closed without merging**
