### PR TITLE
if semicolon

### PR DESCRIPTION
**Pull request by williangaspar**
Thanks to @mmarchini now it's working

### CODE REVIEW

**Comment by mmarchini** [comment]
These changes to `src.parser.yy` should result in the expected behavior: 

```diff
diff --git src/parser.yy src/parser.yy
index a5620b7..13bbc74 100644
--- src/parser.yy
+++ src/parser.yy
@@ -92,7 +92,7 @@ void yyerror(bpftrace::Driver &driver, const char *s);
 %type <ast::Predicate *> pred
 %type <ast::Ternary *> ternary
 %type <ast::StatementList *> block stmts
-%type <ast::Statement *> stmt
+%type <ast::Statement *> block_stmt stmt
 %type <ast::Expression *> expr
 %type <ast::Call *> call
 %type <ast::Map *> map
@@ -169,16 +169,21 @@ block : "{" stmts "}"     { $$ = $2; }
       | "{" stmts ";" "}" { $$ = $2; }
       ;

-stmts : stmts ";" stmt { $$ = $1; $1->push_back($3); }
-      | stmt           { $$ = new ast::StatementList; $$->push_back($1); }
+stmts : stmts ";" stmt            { $$ = $1; $1->push_back($3); }
+      | stmts ";" block_stmt stmt { $$ = $1; $1->push_back($3); $1->push_back($4); }
+      | stmts ";" block_stmt      { $$ = $1; $1->push_back($3); }
+      | block_stmt                { $$ = new ast::StatementList; $$->push_back($1); }
+      | stmt                      { $$ = new ast::StatementList; $$->push_back($1); }
       ;

+block_stmt : IF "(" expr ")" block  { $$ = new ast::If($3, $5); }
+           | IF "(" expr ")" block ELSE block { $$ = new ast::If($3, $5, $7); }
+           | UNROLL "(" INT ")" block { $$ = new ast::Unroll($3, $5); }
+           ;
+
 stmt : expr         { $$ = new ast::ExprStatement($1); }
      | map "=" expr { $$ = new ast::AssignMapStatement($1, $3); }
      | var "=" expr { $$ = new ast::AssignVarStatement($1, $3); }
-     | IF "(" expr ")" block  { $$ = new ast::If($3, $5); }
-     | IF "(" expr ")" block ELSE block { $$ = new ast::If($3, $5, $7); }
-     | UNROLL "(" INT ")" block { $$ = new ast::Unroll($3, $5); }
      ;

 expr : INT             { $$ = new ast::Integer($1); }
```

Yacc will look like this:

```c
stmts : stmts ";" stmt            { $$ = $1; $1->push_back($3); }
      | stmts ";" block_stmt stmt { $$ = $1; $1->push_back($3); $1->push_back($4); }
      | stmts ";" block_stmt      { $$ = $1; $1->push_back($3); }
      | block_stmt                { $$ = new ast::StatementList; $$->push_back($1); }
      | stmt                      { $$ = new ast::StatementList; $$->push_back($1); }
      ;

block_stmt : IF "(" expr ")" block  { $$ = new ast::If($3, $5); }
           | IF "(" expr ")" block ELSE block { $$ = new ast::If($3, $5, $7); }
           | UNROLL "(" INT ")" block { $$ = new ast::Unroll($3, $5); }
           ;

stmt : expr         { $$ = new ast::ExprStatement($1); }
     | map "=" expr { $$ = new ast::AssignMapStatement($1, $3); }
     | var "=" expr { $$ = new ast::AssignVarStatement($1, $3); }
     ;
```

And it works for several cases (with and without semicolon after if/else blocks):

```
# ./src/bpftrace -e 'BEGIN { @s = ""; if ( comm == "") { @s = comm }; exit() }'
Attaching 1 probe...
@s:

# ./src/bpftrace -e 'BEGIN { @s = ""; if ( comm == "") { @s = comm } exit() }'
Attaching 1 probe...
@s:

# ./src/bpftrace -e 'BEGIN { @s = ""; if ( comm != "") { @s = comm; exit() } }'
Attaching 1 probe...
@s: bpftrace

# ./src/bpftrace -e 'BEGIN { if ( comm != "") { @s = comm; exit() } }'
Attaching 1 probe...
@s: bpftrace
```

**Comment by williangaspar** [comment]
```
BEGIN
{
    @a = 0;
    @b = 0;
}

tracepoint:syscalls:sys_enter_nanosleep
{
   	@a = @a + 1;

	if (10 == 20){
	    printf("this is it\n");
	}
	
	if ( @a % 2 == 0){
	    printf("this is it 2\n");
	} else {
	    printf("this is not it\n");
	}
	
	@b = @b + 1;
	
	if (130 == 20){
	    printf("this is it 3\n");
	}
	
	printf("hi there\n")

}
```

this code doesn't run, unfortunately. I've tried similar things, I think the problem with this kind of approach is that we are basically mapping out cases and not creating generic rules. Maybe that's the way to go, but I'm not sure.

**Comment by mmarchini** [comment]
Another attempt:

```diff
diff --git src/parser.yy src/parser.yy
index a5620b7..1f0cea0 100644
--- src/parser.yy
+++ src/parser.yy
@@ -91,8 +91,8 @@ void yyerror(bpftrace::Driver &driver, const char *s);
 %type <ast::Probe *> probe
 %type <ast::Predicate *> pred
 %type <ast::Ternary *> ternary
-%type <ast::StatementList *> block stmts
-%type <ast::Statement *> stmt
+%type <ast::StatementList *> block stmts block_stmts
+%type <ast::Statement *> block_stmt stmt
 %type <ast::Expression *> expr
 %type <ast::Call *> call
 %type <ast::Map *> map
@@ -169,16 +169,24 @@ block : "{" stmts "}"     { $$ = $2; }
       | "{" stmts ";" "}" { $$ = $2; }
       ;

-stmts : stmts ";" stmt { $$ = $1; $1->push_back($3); }
-      | stmt           { $$ = new ast::StatementList; $$->push_back($1); }
+stmts : stmts ";" stmt             { $$ = $1; $1->push_back($3); }
+      | stmts ";" block_stmts stmt { $$ = $1; $1->insert($1->end(), $3->begin(), $3->end()); $1->push_back($4); }
+      | stmts ";" block_stmts      { $$ = $1; $1->insert($1->end(), $3->begin(), $3->end()); }
+      | block_stmts                { $$ = $1; }
+      | stmt                       { $$ = new ast::StatementList; $$->push_back($1); }
       ;

+block_stmts : block_stmts block_stmt     { $$ = $1; $1->push_back($2); }
+            | block_stmt                 { $$ = new ast::StatementList; $$->push_back($1); }
+
+block_stmt : IF "(" expr ")" block  { $$ = new ast::If($3, $5); }
+           | IF "(" expr ")" block ELSE block { $$ = new ast::If($3, $5, $7); }
+           | UNROLL "(" INT ")" block { $$ = new ast::Unroll($3, $5); }
+           ;
+
 stmt : expr         { $$ = new ast::ExprStatement($1); }
      | map "=" expr { $$ = new ast::AssignMapStatement($1, $3); }
      | var "=" expr { $$ = new ast::AssignVarStatement($1, $3); }
-     | IF "(" expr ")" block  { $$ = new ast::If($3, $5); }
-     | IF "(" expr ")" block ELSE block { $$ = new ast::If($3, $5, $7); }
-     | UNROLL "(" INT ")" block { $$ = new ast::Unroll($3, $5); }
      ;

 expr : INT             { $$ = new ast::Integer($1); }

```

Yacc rules:

```c
stmts : stmts ";" stmt             { $$ = $1; $1->push_back($3); }
      | stmts ";" block_stmts stmt { $$ = $1; $1->insert($1->end(), $3->begin(), $3->end()); $1->push_back($4); }
      | stmts ";" block_stmts      { $$ = $1; $1->insert($1->end(), $3->begin(), $3->end()); }
      | block_stmts                { $$ = $1; }
      | stmt                       { $$ = new ast::StatementList; $$->push_back($1); }
      ;

block_stmts : block_stmts block_stmt     { $$ = $1; $1->push_back($2); }
            | block_stmt                 { $$ = new ast::StatementList; $$->push_back($1); }

block_stmt : IF "(" expr ")" block  { $$ = new ast::If($3, $5); }
           | IF "(" expr ")" block ELSE block { $$ = new ast::If($3, $5, $7); }
           | UNROLL "(" INT ")" block { $$ = new ast::Unroll($3, $5); }
           ;

stmt : expr         { $$ = new ast::ExprStatement($1); }
     | map "=" expr { $$ = new ast::AssignMapStatement($1, $3); }
     | var "=" expr { $$ = new ast::AssignVarStatement($1, $3); }
     ;
```

**Comment by williangaspar** [comment]
Yep! That will do it!

**Comment by brendangregg** [comment]
Works for me, thanks!

**Pull request merged**
