### PR TITLE
Add bug report issue template

### PR DESCRIPTION
**Pull request by ajor**
I just wanted something that prompts people to provide the versions they're using. Is there anything else we should ask for here?

### CODE REVIEW

**Comment by fbs** [comment]
+1 on issue template. 

I want to extend the `--info` flag to include a lot more system info, like:

- uname
- llvm version
- compile flags
- version number
- more bpf features (#1152 starts on that)

**Comment by fbs** [comment]
A note like "bpftrace is under active development, not all distros ship the most recent version yet. Please make sure you have the last release or master" might be helpful too

**Comment by javierhonduco** [comment]
Great idea!! 😄 Should we add the exact commands we'd like people to run e.g. `uname -a`, or `cat /etc/os-release`, etc

**Comment by danobi** [comment]
+1 on asking for `bpftrace --info` output too.

**Comment by fbs** [comment]
Just opened #1167 to extend the `--info` flag

**Comment by mmarchini** [comment]
:+1: on adding a bug report issue template. FWIW, this is the template we use on Node.js: https://raw.githubusercontent.com/nodejs/node/master/.github/ISSUE_TEMPLATE/1-bug-report.md

GitHub support HTML commenting, so we can add some instructions as comments if we want (also a `bpftrace is under active development, not all distros ship the most recent version yet. Please make sure you have the last release or master` message as @fbs suggested).

**Comment by danobi** [comment]
Commandeered in #1301.

**Pull request closed without merging**
