### PR TITLE
v0.20.0 release

### PR DESCRIPTION
**Pull request by viktormalik**

### CODE REVIEW

**Review by fbs — APPROVED** [review]

**Review by jordalgo — APPROVED** [review]

**Review by ajor — APPROVED** [review]

**Comment by ajor** [comment]
Just noticed that CI for the Fedora build is failing on master - we should probably fix that before the release to confirm that bpftrace can still actually be built on Fedora.

**Comment by ajor** [comment]
Good to know it's not our fault then, but the reason I'm a little concerned is that our Fedora build did break last week despite the other distros still working: https://github.com/iovisor/bpftrace/pull/2940

As long as bpftrace still builds on Fedora it's fine - just don't want to end up in a situation where a release doesn't compile

**Review by danobi — APPROVED** [review]
:fireworks:

**Comment by viktormalik** [comment]
Turns out that the Fedora issue is in a package which we don't need at all. I updated our Dockerfile to only install the minimal packages necessary, see #2945. I'd like to merge that (and run CI) before doing the release.

**Pull request merged**
