### PR TITLE
bpftrace adaptations of several iovisor/bcc tcp*.py tools

### PR DESCRIPTION
**Pull request by dalehamel**
This is an initial conversion of several of bcc's tcp tracing utilities:

* tcpretrans.bt, an adaptation of tcpretrans.py
* tcpdrop.bt, an adaptation of tcpdrop.py
* tcpaccept.bt, an adaptation of tcpaccept.py
* tcpconnect.bt, an adaptation of tcpconnect.bt

I have ported over bcc's manpages, and adjusted them according to https://github.com/iovisor/bpftrace/issues/245#issuecomment-441395624

For attribution, I've preserved the comment headers from the bcc tools, and added myself as author of the adapted script, but preserving credit to prior authors for their contributions to the technique. I've preserved the copyrights of the original tools. Not too sure what's customary / appropriate here so please let me know if anything should be adjusted.

I've modified the manpages in a similar way to other bcc -> bpftrace manpages.

Work to do still:

* [x] Another pass of manpages, ensuring all fields line up
* [x] Side-by-side comparisons of bcc vs bpftrace version to ensure all fields are in correct column
* [x] example.txt for each tool here, in-line with existing tools

### CODE REVIEW

**Comment by brendangregg** [comment]
Haven't checked them all yet, but to answer a Q: looks like these are based on bcc tools but not copies of bcc code, so my inclination would be to change the copyright to you, but keep in the tool a comment to say that the tool originated from bcc -- which also directs people to a more complex tool if they want.

**Comment by dalehamel** [comment]
> so my inclination would be to change the copyright to you

Done, and I've left a comment in the header block of each indicating that it is a bpftrace version of a bcc tool of the same name.

I have made some progress on #30 in #269, so it might be worth holding off on merging this until I have pushed that over the finish line.

Then again, I don't mind doing another PR to simplify these to use `ntop` once that functionality is merged.

**Comment by dalehamel** [comment]
I'm going to wait on #269 before merging this, as it cleans it up a lot. For example, `tcpaccept.bt` can be written as:

```
...
kretprobe:inet_csk_accept
{
  $sk = ((sock *) retval);
  $af = $sk->__sk_common.skc_family;
  if ( $af ==2 ) {
    $daddr = ntop($af, $sk->__sk_common.skc_daddr);
    $saddr = ntop($af, $sk->__sk_common.skc_rcv_saddr);
    $lport = $sk->__sk_common.skc_num;
    $dport = $sk->__sk_common.skc_dport;
    $qlen  = $sk->sk_ack_backlog;
    $qmax  = $sk->sk_max_ack_backlog;

    // Destination port is big endian, it must be flipped
    $dport = ($dport >> 8) | (($dport << 8) & 0x00FF00);

    time("%H:%M:%S ");
    printf("%-8d %-12s ", pid, comm);
    printf("%s %6d ", $daddr, $dport);
    printf("%s %8d ", $saddr, $lport);
    printf("%-4d%-4d\n", $qlen, $qmax);
  }
}
```

This will also make aligning the columns much easier, as they will be a more predictable maximum fixed-width.

**Comment by dalehamel** [comment]
I've updated these tools to use `ntop` now that #269 has been merged, I also simplified them and fixed a few typos I noticed. I'll do another pass for typos and formatting and any other guidelines for contributing tools, but aside from that I think this should be ready to merge.

**Comment by dalehamel** [comment]
`perl -e 'print "A"x80 . "\n"'`

Thanks for the tip, nice little "char yardstick". I hadn't thought to check total screen size, I guess my terminal might be oddly sized as it didn't quite overflow for me. I ran it past my other scripts, and other than `tcpdrop.bt` they are all fine, but I notice `tcpdrop.py` is wider than 80 when I run it as well.

> Since it's QLEN and QMAX, and these are pretty useful for accept and knowing when we're busting our listen queue / backlog ... Here's a possible solution: :-)

I like you're idea of the `BL` for backlog column, and agree it's a good default. I like your solution and have adopted it.

> I can see an argument that they should be default too

I can PR this over for the bcc tool to keep them in sync if you like, but it's a pretty trivial change either way.

I noticed a couple of other cases where the example output didn't match the formatting for the new column width / header order, and a couple of docs that mentioned bcc examples that don't apply because they aren't supported (yet) in bpftrace, such as reading the full tcp state from the socket buffer.

I've kept my changes in a separate commit for easier review, but can squash it before merging if this is without further issues and is approved.

**Comment by brendangregg** [comment]
Thanks; I think there's a %7s PID vs a %6s pid in tcpaccept.bt.

**Comment by dalehamel** [comment]
> Thanks; I think there's a %7s PID vs a %6s pid in tcpaccept.bt.

Fixed, nice catch.

**Comment by brendangregg** [comment]
Thanks!

**Pull request merged**
