### PR TITLE
bash command completions

### PR DESCRIPTION
**Pull request by williangaspar**

### CODE REVIEW

**Comment by brendangregg** [comment]
I can't get this to work. Maybe I'm doing it wrong. Can you provide a screenshot and more instructions on how to get some completions to work?

I'd put it in /etc/bash_completions.d, started a new shell, sourced it, then tried:

```
bpftrace -e 'kp<tab>
bpftrace -e 'kprobe:vfs_r<tab>
```

But neither of them did anything.

**Comment by mmarchini** [comment]
Tested here, it seems to be working (as root). Steps I took:

1. Install bpftrace with `sudo make install`
2. Make sure I'm root (`sudo su`)
3. `source bpftrace-completion.sh`

```
# bpftrace -e 'tracepoint:ra<tab>
tracepoint:random:add_device_randomness  tracepoint:random:extract_entropy        tracepoint:random:mix_pool_bytes_nolock  tracepoint:ras:aer_event                 tracepoint:ras:non_standard_event
tracepoint:random:add_disk_randomness    tracepoint:random:extract_entropy_user   tracepoint:random:push_to_pool           tracepoint:ras:arm_event                 tracepoint:raw_syscalls:sys_enter
tracepoint:random:add_input_randomness   tracepoint:random:get_random_bytes       tracepoint:random:random_read            tracepoint:ras:extlog_mem_event          tracepoint:raw_syscalls:sys_exit
tracepoint:random:credit_entropy_bits    tracepoint:random:get_random_bytes_arch  tracepoint:random:urandom_read           tracepoint:ras:mc_event
tracepoint:random:debit_entropy          tracepoint:random:mix_pool_bytes         tracepoint:random:xfer_secondary_pool    tracepoint:ras:memory_failure_event
```

Root is required because `bpftrace -l` doesn't work with unprivileged users. Overall I don't see workarounds here, unless we save which kprobes and tracepoints are available in an unprivileged location.

**Comment by mmarchini** [comment]
@williangaspar when there's only one completion option and I hit tab, it closes the single quote: `bpftrace -e 'tracepoint:random:mix_pool_bytes_n<tab>` becomes `bpftrace -e 'tracepoint:random:mix_pool_bytes_nolock'`. I'm not sure if this should be the expected behavior.

Also, `bpftrace -e 'tracepoint:random:mix_pool_bytes_nolock {} kpro<tab><tab>'` becomes `bpftrace -e 'kprobe:'`, which is a bug.

**Comment by williangaspar** [comment]
Closing, if anyone wants to implement this, please fill free to take over.

**Pull request closed without merging**
