### PR TITLE
Support anonymous struct/union in BTF::type_of()

### PR DESCRIPTION
**Pull request by mmisono**
Support access to a field inside an anonymous struct such as `mmap` in
`mm_struct`.

```
struct mm_struct {
  struct {
    struct vm_area_struct *mmap;
    struct rb_root mm_rb;
    ...
  }
  ...
}
```

This fixes the following error.

```
% bpftrace -b -e 'BEGIN { printf("%lx\n", curtask->mm->mmap->vm_start); }'
stdin:1:25-44: ERROR: Unknown struct/union: 'struct vm_area_struct'
BEGIN { printf("%lx\n", curtask->mm->mmap->vm_start); }
                        ~~~~~~~~~~~~~~~~~~~
```

### CODE REVIEW

**Comment by mmisono** [comment]
@olsajiri Could you take a look when you have time? I'm new to BTF and just found the problem.

**Comment by olsajiri** [comment]
sry for delay.. checking

**Comment by olsajiri** [comment]
@mmisono looks good, any chance you could add annonymous struct/union to tests/btf_data.h
and add appropriate test to `TEST_F(clang_parser_btf, btf_field_struct)` ? thanks

**Comment by mmisono** [comment]
Thanks for the review. I'll work on it.

**Comment by mmisono** [comment]
@olsajiri
How did you get the [this BTF data](https://github.com/iovisor/bpftrace/blob/4fe9064cfe7f3694bc5b1dd4fa164660bc8422b0/tests/btf_data.h#L21-L45)? I can get BTF data by pahole or clang, but not sure how exactly reproduce it. Is it constructed manually?

**Comment by mmisono** [comment]
I found that the following gave the same data. -- sorry to bother you.

```c
struct Foo1 {
  int  a;
  char b;
  long c;
};

struct Foo2 {
  int         a;
  struct Foo1 f;
};

struct Foo3 {
  struct Foo1 *foo1;
  struct Foo2 *foo2;
};

struct Foo3 f3;
```

```
% clang -target bpf -g -c a.c
% llvm-objcopy --dump-section .BTF=a.btf a.o
% hexdump -C a.btf
00000000  9f eb 01 00 18 00 00 00  00 00 00 00 c0 00 00 00  |................|
00000010  c0 00 00 00 34 00 00 00  01 00 00 00 03 00 00 04  |....4...........|
00000020  10 00 00 00 06 00 00 00  02 00 00 00 00 00 00 00  |................|
00000030  08 00 00 00 03 00 00 00  20 00 00 00 0a 00 00 00  |........ .......|
00000040  04 00 00 00 40 00 00 00  0c 00 00 00 00 00 00 01  |....@...........|
00000050  04 00 00 00 20 00 00 01  10 00 00 00 00 00 00 01  |.... ...........|
00000060  01 00 00 00 08 00 00 01  15 00 00 00 00 00 00 01  |................|
00000070  08 00 00 00 40 00 00 01  1e 00 00 00 02 00 00 04  |....@...........|
00000080  18 00 00 00 06 00 00 00  02 00 00 00 00 00 00 00  |................|
00000090  23 00 00 00 01 00 00 00  40 00 00 00 25 00 00 00  |#.......@...%...|
000000a0  02 00 00 04 10 00 00 00  2a 00 00 00 07 00 00 00  |........*.......|
000000b0  00 00 00 00 2f 00 00 00  08 00 00 00 40 00 00 00  |..../.......@...|
000000c0  00 00 00 00 00 00 00 02  01 00 00 00 00 00 00 00  |................|
000000d0  00 00 00 02 05 00 00 00  00 46 6f 6f 31 00 61 00  |.........Foo1.a.|
000000e0  62 00 63 00 69 6e 74 00  63 68 61 72 00 6c 6f 6e  |b.c.int.char.lon|
000000f0  67 20 69 6e 74 00 46 6f  6f 32 00 66 00 46 6f 6f  |g int.Foo2.f.Foo|
00000100  33 00 66 6f 6f 31 00 66  6f 6f 32 00              |3.foo1.foo2.|
0000010c
```

**Comment by olsajiri** [comment]
@mmisono looks great, I should have added that 'generated by' info like you did, thanks for that

**Pull request merged**
