### PR TITLE
add mips64 reg

### PR DESCRIPTION
**Pull request by George-Hu**
##### Checklist

- [ ] Language changes are updated in `docs/reference_guide.md`
- [ ] User-visible and non-trivial changes updated in `CHANGELOG.md`
- [ ] The new behaviour is covered by tests

### CODE REVIEW

**Comment by mmisono** [comment]
Could you update the CHANGELOG.md?

**Comment by mmisono** [comment]
Also, bpftrace has architecture-specific tests for register access: https://github.com/iovisor/bpftrace/blob/master/tests/runtime/intptrcast . It would be great to add MIPS tests as well.

**Comment by danobi** [comment]
Yeah, some basic tests would be nice

**Comment by fbs** [comment]
@George-Hu  can you add in a changelog entry?

Tests would be nice too

**Comment by fbs** [comment]
#1708 for the changelog

**Pull request closed without merging**
