### PR TITLE
Fix leaks from Bison memory allocations

### PR DESCRIPTION
**Pull request by oazizi000**
The Bison code creates a lot of objects with the `new` operator. These all end up causing memory leaks, because there is no corresponding call to `delete`. This change resolves this issue by using `std::unique_ptr` to create managed objects that will be destroyed once they are no longer needed.

This is a large commit, but is mostly mechanical changes, no logical change is intended.

##### Checklist

- [ ] Language changes are updated in `docs/reference_guide.md`
- [ ] User-visible and non-trivial changes updated in `CHANGELOG.md`
- [ ] The new behaviour is covered by tests

### CODE REVIEW

**Comment by fbs** [comment]
Thanks for looking into this? Have you seen the discussion in #1055 ?

**Comment by oazizi000** [comment]
> Thanks for looking into this! Have you seen the discussion in #1055 ?

@fbs I had not seen #1055, so thanks for pointing that out! Looks like I've gone down a very similar road to what was discussed in that thread, so happy to see that (provides some confirmation that it's the right approach).

This particular PR still has some issues that I have not been able to reproduce locally, so it's not passing the checks. Once I get things figured out, I can push out an update community to review and discuss, as a potential fix. If there's a pending fix from #1055, I'm obviously happy to go with that as well.

**Comment by fbs** [comment]
Looks like the build issue is exactly the thing discussed in #1055, a bison doesn't move http://www.comrite.com/wp/c11-stdunique_ptr-as-semantic-value-in-bison-c-mode/ . 

It looks like we'd loose ubuntu 18.04 (lts) if we do this as it still has 3.0.x and no backports, so this might have to wait a few more years.

I think the delete approach from 1055 is better for now. Its a bit ugly but easy enough to implement.

**Comment by fbs** [comment]
The  manual memory management is in  so I think thats the way to go for now. Moving to smart pointers would be nice but bumping bison versions means dropping ubuntu which we can't do just yet.

Maybe we can have AST constructors dedicated to the parser  that convert the raw pointers into smart pointers untill we can update bison.

**Pull request closed without merging**
