### PR TITLE
Update build instructions for ubuntu

### PR DESCRIPTION
**Pull request by fbs**
Just tested this on 18.04, 18.10 and 19.04 with builds from master.

### CODE REVIEW

**Comment by fbs** [comment]
Looks like this fixes #389. #76 too if scope is limited to 18.04 and newer

**Comment by brendangregg** [comment]
Thanks; so llvm got updated? just using the Ubuntu version for llvm-7 works now?

**Comment by fbs** [comment]
Yes, I've tested (i.e. copy paste instructions) it on a newly created 18.04 and it works.

**Comment by brendangregg** [comment]
thanks!

**Pull request merged**
