### PR TITLE
[WIP] str() to accept optional length

### PR DESCRIPTION
**Pull request by Birch-san**
Intended to fulfil https://github.com/iovisor/bpftrace/issues/199.  
It's pretty close to working, but I think I need to ask for help at this point.

Integer literals work:

```bash
bpftrace -e 'tracepoint:syscalls:sys_enter_write /pid == 23506/ { printf("<%s>\n", str(args->buf, 2));  }'
# type pwd into a terminal
<p>
<w>
<d>
# it printed 1 character instead of the 2 we requested; probably probe_read_str replaces final byte with a NULL. fixable.
```

But it doesn't seem to be able to use items from structs (e.g. `args->count`):

```bash
sudo bpftrace -e 'tracepoint:syscalls:sys_enter_write /pid == 6034/ { printf("<%s>\n", str(args->buf, args->count)); }'
Attaching 1 probe...
Error loading program: tracepoint:syscalls:sys_enter_write (try -v)
```

[The verbose output](https://gist.github.com/Birch-san/010ada4873e646a11b6a3c2bbfcc0d88) shows the error:

```
R2 min value is negative, either use unsigned or 'var &= const'
````

I think R2 is the size arg to `bpf_probe_read_str(void *dst, int size, const void *unsafe_ptr)`.  
I think it wants me to prove that the size will always be positive.

This is despite the fact that I've already cast it to a 64-bit _unsigned_:

```c++
b_.CreateStore(
  b_.CreateIntCast(expr_, b_.getInt64Ty(), false),
  strlen);
```

I also tried using a bitmask:

```c++
b_.CreateStore(
  b_.CreateAnd(
    b_.CreateIntCast(expr_, b_.getInt64Ty(), false),
    0xffffffff),
  strlen);
```

The bitmask changed the error to:

```
R2 unbounded memory access, use 'var &= const' or 'if (var < const)'
```

I also tried using CreateMaxNum():

```c++
b_.CreateStore(
  b_.CreateMaxNum(
    b_.getInt64(0),
    b_.CreateIntCast(expr_, b_.getInt64Ty(), false),
    "ensure_positive"),
  strlen);
```

CreateMaxNum() changed the error to:

```
Segmentation fault
```

I also tried using a condition:

```c++
call.vargs->at(1)->accept(*this);
Value *len_u64 = b_.CreateIntCast(expr_, b_.getInt64Ty(), false);

Function *parent = b_.GetInsertBlock()->getParent();
BasicBlock *positive = BasicBlock::Create(module_->getContext(), "positive", parent);
BasicBlock *negative = BasicBlock::Create(module_->getContext(), "negative", parent);
BasicBlock *done = BasicBlock::Create(module_->getContext(), "done", parent);
b_.CreateCondBr(
  b_.CreateICmpUGE(len_u64, b_.getInt64(0), "if_positive"),
  positive,
  negative);

b_.SetInsertPoint(positive);
b_.CreateStore(len_u64, strlen);
b_.CreateBr(done);

b_.SetInsertPoint(negative);
b_.CreateStore(b_.getInt64(1), strlen);
b_.CreateBr(done);

b_.SetInsertPoint(done);
```

But this resulted in the same:

```
R2 min value is negative, either use unsigned or 'var &= const'
```

Does anybody here have any ideas on how to overcome this error?

### CODE REVIEW

**Comment by Birch-san** [comment]
Here's the -dd output:

https://gist.github.com/Birch-san/c478887d8db25f58a2b8280939349882

**Comment by brendangregg** [comment]
Everything you've tried makes sense to me, and I've followed a similar path when developing earlier features, where I've hit the same errors before. I wish I documented them in https://github.com/iovisor/bpftrace/blob/master/docs/internals_development.md -- someone should at some point: have a section for each error message and what it means with suggested solutions.

It helps to read https://github.com/torvalds/linux/blob/master/kernel/bpf/verifier.c . Eg:

```
		if (reg->umax_value >= BPF_MAX_VAR_SIZ) {
			verbose(env, "R%d unbounded memory access, use 'var &= const' or 'if (var < const)'\n",
				regno);
			return -EACCES;
		}
```

And BPF_MAX_VAR_SIZ (where's the E???) is (1 << 29). So yeah, that would suggest that using a bitmask is a good idea, but you're already trying that. Is the b_.CreateIntCast() necessary? Can we bitmask to expr_ directly?

What you wrote serves as good documentation for diagnosing this type of issues anyway, so if we figure out the solution it might be nice to copy what you wrote and put it in internals_development.md.

**Comment by Birch-san** [comment]
Thanks for the hint.

I tried omitting the 64-bit cast; no improvement.* I also tried moving the bit mask to be as late as possible (wrapping it around `b_.CreateLoad(strlen)`), so that it's definitely constraining the arg on `b_.CreateProbeReadStr()`. No improvement.*  
*These changes randomized the error to one of the other error messages already reported. I didn't document exactly what change resulted in which error. Might be an idea for my next pass.

I've found the bpf self-test that reproduces the error:  
`R2 min value is negative, either use unsigned or 'var &= const'`  
https://github.com/torvalds/linux/blob/master/tools/testing/selftests/bpf/test_verifier.c#L7378

It's followed by other assertions on bounds, and finally a "correct bounds" test (which hopefully reveals how to make this thing work):
https://github.com/torvalds/linux/blob/master/tools/testing/selftests/bpf/test_verifier.c#L7419

I followed the history of the test (it's undergone some changes in wording) to when it was originally committed, with accompanying implementation code:
https://github.com/torvalds/linux/commit/06c1c049721a995dee2829ad13b24aaf5d7c5cce#diff-1d760ce3dbf1aad3a5e223501e8aaa7bR3622

**Comment by Birch-san** [comment]
Ah, I think I understand.

First, a recap... we start with this error:

```
R2 min value is negative, either use unsigned or 'var &= const'
```

The verifier wants proof that it's non-negative.  
So, we bitmask with 0xFFFFFFFF, and we get to the next error:

```
R2 unbounded memory access, use 'var &= const' or 'if (var < const)'
```

So the verifier's _satisfied with the minimum bound_, but wants a _maximum bound as well_.

The [snippet you posted](https://github.com/torvalds/linux/blob/master/kernel/bpf/verifier.c#L2256) was right on the money:

```c
if (reg->umax_value >= BPF_MAX_VAR_SIZ) {
	verbose(env, "R%d unbounded memory access, use 'var &= const' or 'if (var < const)'\n",
		regno);
	return -EACCES;
}
```

And as you say: [`BPF_MAX_VAR_SIZ` is 1 << 29](https://github.com/torvalds/linux/blob/82aa4671516a3203261c835e98c3eecab10c994d/include/linux/bpf_verifier.h#L22). The upper limit exists to provide protection against overflows.

So, I think it **is** responding to the bitmask, and we just need to tweak the bitmask (or conditional branching) to ensure that the largest possible value is `1 << 29 - 1`. Will give it a try soon.

**Comment by Birch-san** [comment]
okay, the smaller bitmask (`(1ULL << 29) - 1` = `0x1FFFFFFF`) certainly seems to have had an effect.
_side-note: [how to print unsigned 64-bit ints as hex](https://gist.github.com/Birch-san/d21f4ae40be9eec598ec3fdd47b0c3c7)_.

We now get a new error:

```
invalid stack type R1 off=-72 access_size=536870911
```

536870911=0x1FFFFFFF (i.e. my bitmask)

[Verbose output](https://gist.github.com/Birch-san/f5c41379e22cf7a6d680707a0badda88)

**Comment by Birch-san** [comment]
I think it may be impossible to write a valid program.

[Here's](https://github.com/torvalds/linux/blob/master/kernel/bpf/verifier.c#L2032) where the verifier kicks us out:

```c++
off = reg->off + reg->var_off.value;
if (off >= 0 || off < -MAX_BPF_STACK || off + access_size > 0 ||
    access_size < 0 || (access_size == 0 && !zero_size_allowed)) {
	verbose(env, "invalid stack type R%d off=%d access_size=%d\n",
		regno, off, access_size);
	return -EACCES;
}
```

We encounter...

```
invalid stack type R1 off=-72 access_size=536870911
```

...because `off + access_size > 0`.

The stack probably looks like this:

- [`static int check_stack_boundary(struct bpf_verifier_env *env, int regno,
				int access_size, bool zero_size_allowed,
struct bpf_call_arg_meta *meta)#L2032`](https://github.com/torvalds/linux/blob/master/kernel/bpf/verifier.c#L2032)
- [`static int check_helper_mem_access(struct bpf_verifier_env *env, int regno, int access_size, bool zero_size_allowed, struct bpf_call_arg_meta *meta)#L2087`](https://github.com/torvalds/linux/blob/master/kernel/bpf/verifier.c#L2087)
- [`static int check_func_arg(struct bpf_verifier_env *env, u32 regno, enum bpf_arg_type arg_type, struct bpf_call_arg_meta *meta)#L2260`](https://github.com/torvalds/linux/blob/master/kernel/bpf/verifier.c#L2260)

The reason our access_size is so high [(equals the bitmask)](https://gist.github.com/Birch-san/f5c41379e22cf7a6d680707a0badda88#file-gistfile1-txt-L51) is because [that's the unsigned maximum of the register](https://github.com/torvalds/linux/blob/master/kernel/bpf/verifier.c#L2261):

```c++
err = check_helper_mem_access(env, regno - 1,
			      reg->umax_value,
zero_size_allowed, meta);
```

…and that's what gets passed all the way down into `check_stack_boundary(…)`.

Ah, I think I'm starting to understand. `probe_read_str` writes into the BPF stack-allocated memory. I only allocated a string buffer of 64 bytes (`STRING_SIZE`) on the stack.

so I either need to parameterise the "length of string buffer", or tighten my bitmask to 64 to ensure the read string fits in the string buffer.

**Comment by Birch-san** [comment]
I tried doing dynamic allocations:

```c++
if (call.func == "str")
{
  AllocaInst *strlen = b_.CreateAllocaBPF(b_.getInt64Ty(), "strlen");
  b_.CreateMemSet(strlen, b_.getInt8(0), sizeof(uint64_t), 1);
  if (call.vargs->size() > 1) {
    call.vargs->at(1)->accept(*this);
    b_.CreateStore(b_.CreateAnd(expr_, 0x1fffffff), strlen);
  } else {
    b_.CreateStore(b_.getInt64(STRING_SIZE), strlen);
  }
  
  AllocaInst *buf = b_.CreateAllocaBPF(b_.getInt8Ty(), b_.CreateLoad(strlen), "str");
  b_.CreateMemSet(buf, b_.getInt8(0), b_.CreateLoad(strlen), 1);
  call.vargs->front()->accept(*this);
  b_.CreateProbeReadStr(buf, b_.CreateLoad(strlen), expr_);
  b_.CreateLifetimeEnd(strlen);
  expr_ = buf;
}
```

Alas:

`str(args->buf, args->count)` encounters a sefault. No `-ve` was able to be generated, but here's [the `-dd`](https://gist.github.com/Birch-san/d277fb6692fe36fff4e750e12ebff4c3)).

`str(args->buf, 1)` encounters `invalid stack off=14 size=1`. [`-ve` here](https://gist.github.com/Birch-san/7c67befeb79c4fa24d1402c59d94e49f), [`-dd` here](https://gist.github.com/Birch-san/b64c159314390a1f16a077657b036d9b).

`str(args->buf, 64)` [works fine](https://gist.github.com/Birch-san/cd5771fe7822980498b383cdf1e62fdd). [63 does not](https://gist.github.com/Birch-san/4cf72992d24ab2d67b0e42f56101b8db).

So, something (printf?)'s trying to begin a read (at least?) 64 bytes out of my string buffer, and in the 1–63 case: I'm not allocating enough string buffer to accommodate that.

Maybe that's the key to solving the segfault in the case of `str(args->buf, args->count)`. Or maybe I'm barking up the wrong try.

also: it'd be educational to see what happens if I constrain args->count to a 0xFF bitmask, since a lot of things (my string buffer allocation, and perhaps printf) are working with 64.

**Comment by Birch-san** [comment]
[constraining args->count to a 0x0000003F bitmask](https://github.com/iovisor/bpftrace/pull/241/commits/a89b910cc3e624f20c1765e16846cc9f0b7f404f) (e.g. <=63) passes the verifier.

[Here's the `-v`](https://gist.github.com/Birch-san/4d672ea852b19fc1c6e3a5fd8698fcc5), [`-dd`](https://gist.github.com/Birch-san/7c8ce70f6a637962e60ca88b61537fcb), and output:

```bash
sudo bpftrace -e 'tracepoint:syscalls:sys_enter_write /pid == 6034/ { printf("%d:<%s>\n", args->count, str(args->buf, args->count)); }'
Running...
1:<p>
1:<w>
1:<d>
1:<
>
30:</home/anon/git/bpftrace/build
>
116:<[01;>
```

```bash
anon@anon-VirtualBox:~/git/bpftrace/build$ pwd
/home/anon/git/bpftrace/build
anon@anon-VirtualBox:~/git/bpftrace/build$ 
```

**Comment by Birch-san** [comment]
I think part of the problem is a friction between semantic_analyser and codegen_llvm.

semantic_analyser is responsible for populating bpftrace_.printf_args_, which ultimately determines in codegen_llvm:

- how many bytes we allocate per arg (when allocating the printf_args)
- how many bytes we MEMCPY per arg (when writing the printf_args)

I don't think semantic_analyser should be in charge of that; it couldn't know up-front how big a changing string can be.

codegen_llvm could only learn the final size of the string by using `call.vargs->at(n)` and running the visitor on it. we do this already, but separately from measuring/allocating the struct. maybe we'll be forced to couple those steps.

**Comment by Birch-san** [comment]
Closed in favor of https://github.com/iovisor/bpftrace/pull/241

**Pull request closed without merging**
