### PR TITLE
Embedded builds: Upgrade to Alpine 3.14, LLVM 11

### PR DESCRIPTION
**Pull request by acj**
This is mostly working, but some of the tests are failing, e.g.:

```
2: [ RUN      ] call.strftime_as_map_value
2: [  FAILED  ] call.strftime_as_map_value
2: 	Command: ../src/bpftrace -v -e 'BEGIN { @[nsecs] = strftime("%m/%d/%y", nsecs); exit();}'
2: 	Expected: @\[[0-9]*\]: [0-9]{2}\/[0-9]{2}\/[0-9]{2}
2: 	Found: INFO: node count: 11\nFailure value returned from cantFail wrapped call\nDynamic loading not supported\nUNREACHABLE executed at /usr/include/llvm11/llvm/Support/Error.h:749!\n
```

Smells like a linking issue with testprogs. I'll keep digging. If anyone has suggestions, please let me know.

##### Checklist

- [ ] Language changes are updated in `docs/reference_guide.md`
- [ ] User-visible and non-trivial changes updated in `CHANGELOG.md`
- [ ] The new behaviour is covered by tests

### CODE REVIEW

**Comment by fbs** [comment]
No llvm 12 for alpine yet? 12 fixes #1305 

> 2: 	Found: INFO: node count: 11\nFailure value returned from cantFail wrapped call\nDynamic loading not supported\nUNREACHABLE executed at /usr/include/llvm11/llvm/Support/Error.h:749!\n
> Smells like a linking issue with testprogs

This example doesn't run a testprog. Apparently llvm wants to dynamic load code somewhere.

Can you try:
```
diff --git a/src/bpforcv2.cpp b/src/bpforcv2.cpp
index 209e08e5..9876625b 100644
--- a/src/bpforcv2.cpp
+++ b/src/bpforcv2.cpp
@@ -14,9 +14,6 @@ BpfOrc::BpfOrc(TargetMachine *TM, DataLayout DL)
       CTX(std::make_unique<LLVMContext>()),
       MainJD(cantFail(ES.createJITDylib("<main>")))
 {
-  MainJD.addGenerator(
-      cantFail(DynamicLibrarySearchGenerator::GetForCurrentProcess(
-          DL.getGlobalPrefix())));
 }
```

I'm pretty sure we don't need this and I think it might fix your error.

**Comment by acj** [comment]
> No llvm 12 for alpine yet?

Unfortunately not. The edge (latest/unstable) repo still has 10 and 11, so it's trailing a bit.

> This example doesn't run a testprog. Apparently llvm wants to dynamic load code somewhere.

Ah, whoops. Most of the failures I saw were related to testprogs, but you're right that it's failing more widely.

I'll give your suggestion a try. Thanks 👍

**Comment by acj** [comment]
Much better. The remaining failures are libclang parsing crashes, specifically in the release build.

```
libclang: crash detected during parsing: {\n  'source_filename' : 'definitions.h'\n  'command_line_args' : ['clang', '-isystem', '/usr/local/include', '-isystem', '/bpftrace/include', '-isystem', '/usr/include', '-nostdinc', '-isystem', '/virtual/lib/clang/include', '-I/lib/modules/5.4.0-1049-azure/build/arch/x86/include', '-I/lib/modules/5.4.0-1049-azure/build/arch/x86/include/generated', '-I/lib/modules/5.4.0-1049-azure/build/include', '-I/lib/modules/5.4.0-1049-azure/build/include', '-I/lib/modules/5.4.0-1049-azure/build/arch/x86/include/uapi', '-I/lib/modules/5.4.0-1049-azure/build/arch/x86/include/generated/uapi', '-I/lib/modules/5.4.0-1049-azure/build/include/uapi', '-I/lib/modules/5.4.0-1049-azure/build/include/generated/uapi', '-include', '/lib/modules/5.4.0-1049-azure/build/include/linux/kconfig.h', '-D__KERNEL__', '-D__BPF_TRACING__', '-D__HAVE_BUILTIN_BSWAP16__', '-D__HAVE_BUILTIN_BSWAP32__', '-D__HAVE_BUILTIN_BSWAP64__', '-DKBUILD_MODNAME="bpftrace"', '-include', 'clang_workarounds.h'],\n  'unsaved_files' : [('definitions.h', '...', 184), ('/bpftrace/include/__stddef_max_align_t.h', '...', 1771), ('/bpftrace/include/float.h', '...', 5192), ('/bpftrace/include/limits.h', '...', 3735), ('/bpftrace/include/stdarg.h', '...', 2025), ('/bpftrace/include/stddef.h', '...', 4499), ('/bpftrace/include/stdint.h', '...', 23390), ('/bpftrace/include/clang_workarounds.h', '...', 921), ('/bpftrace/include/__btf_generated_header.h', '...', 0)],\n  'options' : 1,\n}\n
```

**Comment by Birch-san** [comment]
> No llvm 12 for alpine yet?

Nothing for [v3.14](https://pkgs.alpinelinux.org/packages?name=llvm*-dev&branch=v3.14&arch=x86_64), nor for [edge](https://pkgs.alpinelinux.org/packages?name=llvm*-dev&branch=edge&arch=x86_64)

**Pull request closed without merging**
