### PR TITLE
Allow wildcards for tracepoint categories

### LINKED ISSUE #1212: Allow wildcards to be used in tracepoint categories
eg allow this:
```
tracepoint:syscal*s:sys_enter_op*nat { printf("%s\n", str(args->filename)); }
```

See https://github.com/iovisor/bpftrace/pull/1205#pullrequestreview-375596331 for what code change might look like.

### PR DESCRIPTION
**Pull request by viktormalik**
It is now possible to run e.g. this:

    bpftrace -e 'tracepoint:kvm*:* { @[probe] = count(); }'

Resolves #1212. 

##### Checklist

- [x] Language changes are updated in `docs/reference_guide.md`
- [x] User-visible and non-trivial changes updated in `CHANGELOG.md`

### CODE REVIEW

**Comment by viktormalik** [comment]
Embedded build failed on a uprobe test (cannot open mount ns), which shouldn't be affected by this PR. Not sure why the error occurred, it passed on my fork's branch build.

Also there are clang-format fails in a new test that I copied from an existing one (which contains the same format errors, too).

**Comment by fbs** [comment]
> Embedded build failed on a uprobe test (cannot open mount ns), which shouldn't be affected by this PR. Not sure why the error occurred, it passed on my fork's branch build.

Some tests are still somewhat flaky and fail sporadically,  rerunning it usually  fixes it

> Also there are clang-format fails in a new test that I copied from an existing one (which contains the same format errors, too).

We try to incrementally fix  the formatting errors. So if you touch code you format it. This way we can keep git blame useful.

**Comment by danobi** [comment]
I kicked off another round of embedded tests. Let's see if it passes this time.

> We try to incrementally fix the formatting errors. So if you touch code you format it. This way we can keep git blame useful.

+1

**Comment by viktormalik** [comment]
> I kicked off another round of embedded tests. Let's see if it passes this time.

Thanks, they all passed now.

> We try to incrementally fix the formatting errors. So if you touch code you format it. This way we can keep git blame useful.

Sounds good, ok, fixed. I'll keep this in mind.

**Pull request merged**
