### PR TITLE
Revert "Add "probe_inline" to adoc"

### PR DESCRIPTION
**Pull request by jordalgo**
Reverts bpftrace/bpftrace#3623

### CODE REVIEW

**Review by ajor — APPROVED** [review]

**Comment by ajor** [comment]
I'm not opposed to adding it to the docs, but we'll need to clarify that it's experimental and maybe think of a more descriptive config option name

**Comment by jordalgo** [comment]
Maybe the config name should adhere to the feature gate proposal (https://github.com/bpftrace/bpftrace/issues/3521) if it's still experimental e.g. "unstable_attach_to_inline_funcs"

**Comment by danobi** [comment]
Yes, let's prefix it with `unstable_` so we know by convention it's not "done" yet

**Comment by jordalgo** [comment]
https://github.com/bpftrace/bpftrace/pull/3628

**Pull request merged**
