### PR TITLE
bfd build issues

### PR DESCRIPTION
**Pull request by fbs**
On a fedora system without `binutils-devel` the build fails with
`pthread not found`:

```
-- Please install the libbpf development package (missing: LIBBPF_LIBRARIES LIBBPF_INCLUDE_DIRS)
-- Please install the libbfd development package (missing: LIBBFD_LIBRARIES LIBBFD_INCLUDE_DIRS)
-- Performing Test LIBBFD_DISASM_FOUR_ARGS_SIGNATURE
-- Performing Test LIBBFD_DISASM_FOUR_ARGS_SIGNATURE - Failed
-- Please install the libopcodes development package (missing: LIBOPCODES_LIBRARIES_LIBOPCODES_INCLUDE_DIR)
DIRS)
-- Looking for sys/sdt.h
-- Looking for sys/sdt.h - not found
-- Looking for pthread.h
-- Looking for pthread.h - not found
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Threads (missing: Threads_FOUND)
```

This is  caused by the `CMAKE_REQUIRED_LIBRARIES` being
"leaked" between tests combined with CMP0075 . When testing for threads
cmake still links agains `bfd` and `opcodes` which do not exist and the
test fails. To avoid this we have to clear `CMAKE_REQUIRED_LIBRARIES`
after the test.

### CODE REVIEW

**Comment by olsajiri** [comment]
looks good to me, I tested on my fedora and it fixes the issue
thanks

**Comment by danobi** [comment]
Disclaimer: not a cmake expert

In the root `CMakeLists.txt`, there's a `set(CMAKE_REQUIRED_LIBRARIES bcc)`. Since it appears that variable is global, are we worried about clobbering `bcc` from that list? Would it be better to reset to a saved copy of CMAKE_REQUIRED_LIBRARIES?

**Comment by fbs** [comment]
> Disclaimer: not a cmake expert

Me neither :)

> In the root `CMakeLists.txt`, there's a `set(CMAKE_REQUIRED_LIBRARIES bcc)`. Since it appears that variable is global, are we worried about clobbering `bcc` from that list? Would it be better to reset to a saved copy of CMAKE_REQUIRED_LIBRARIES?

From what I can tell we do not depend on `CMAKE_REQUIRED_LIBRARIES` for our build targets. All our targets have their deps correctly* like:

```
if (STATIC_LINKING)
  target_link_libraries(bpftrace ${LIBBCC_LIBRARIES})
  target_link_libraries(bpftrace ${LIBBPF_LIBRARY_STATIC})
  target_link_libraries(bpftrace ${LIBBCC_LOADER_LIBRARY_STATIC})
else()
  target_link_libraries(bpftrace ${LIBBCC_LIBRARIES})
endif()
target_link_libraries(bpftrace ${LIBELF_LIBRARIES})
```

We do not do something like `LINK_LIBRARIES ${CMAKE_REQUIRED_LIBRARIES}`. So `CMAKE_REQUIRED_LIBRARIES` is only used for the tests we do, like 

```
CheckSymbolExists

The following variables may be set before calling this macro to modify the way the check is run:
CMAKE_REQUIRED_FLAGS = string of compile command line flags
CMAKE_REQUIRED_DEFINITIONS = list of macros to define (-DFOO=bar)
CMAKE_REQUIRED_INCLUDES = list of include directories
CMAKE_REQUIRED_LIBRARIES = list of libraries to link
```

As we do not use this for builds we do not have to save the state, instead we should clear those 4 after use. Every test must make sure the "env" is correct.

In the case of bcc it doesn't really matter as bcc is required, without it bpftrace won't work. But we should probably fix all cases anyway.

This seems to work for bcc. I'll try and fix all cases and put it in a seperate commit.

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index d4a8b6c..0ec438d 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -70,6 +70,8 @@ set(CMAKE_REQUIRED_LINK_OPTIONS -L${LIBBCC_LIBDIR})
 check_symbol_exists(bcc_prog_load "${LIBBCC_INCLUDE_DIRS}/libbpf.h" HAVE_BCC_PROG_LOAD)
 check_symbol_exists(bcc_create_map "${LIBBCC_INCLUDE_DIRS}/libbpf.h" HAVE_BCC_CREATE_MAP)
 check_symbol_exists(bcc_elf_foreach_sym "${LIBBCC_INCLUDE_DIRS}/bcc_elf.h" HAVE_BCC_ELF_FOREACH_SYM)
+set(CMAKE_REQUIRED_LIBRARIES)
+set(CMAKE_REQUIRED_LINK_OPTIONS)

 include(CheckTypeSize)
 set(CMAKE_EXTRA_INCLUDE_FILES linux/bpf.h)
```


* Google tells me that using targets is the correct way to CMAKE. All options you want you set on a target, not "global".

**Comment by fbs** [comment]
Updated @danobi

**Comment by danobi** [comment]
Got it. Thanks for looking into this!

**Pull request merged**
