### PR TITLE
attach to all locations of USDT

### PR DESCRIPTION
**Pull request by kazuho**
Bcc is capable of associating multiple locations (i.e. offsets within an executable) to each probe. However, bpftrace only activates one having the minimal offset.

This PR fixes the issue, changing bpftrace to activate all the offsets being associated to a probe.

This was an issue for me, as I was having multiple locations in my binary calling the same probe, due to the compiler performing inline expansion.

### CODE REVIEW

**Comment by kazuho** [comment]
It seems that CI is failing due to an old version of bcc being used; this PR depends on the API change (of bcc_resolve_global_addr) introduced in  https://github.com/iovisor/bcc/commit/01ee0b61a854e06cb62272ddfbb4eeaf16e9ad7c.

**Comment by danobi** [comment]
Might be a bit before we get bcc 0.11.0 in our builds. #867 gets us bcc 0.10.0 but pins us to alpine 3.10. If we can get that in, I'll try to get us to alpine 3.11 which should get us bcc 0.11.0 for free through the package repos.

**Comment by dalehamel** [comment]
@kazuho this is a great change, do you have time to rebase it?

**Comment by dalehamel** [comment]
we have BCC 12 in CI now at least on github actions (though the iovisor repo is older I think), and perhaps we could check if the method exists like we do others?

**Comment by dalehamel** [comment]
I spoke with @kazuho via email and have agreed to take over this PR for him, i've rebased this branch and am working on integrating it with master.

**Comment by fbs** [comment]
@dalehamel  will have to open a new pr anyway so I'll close this

**Comment by danobi** [comment]
This is already fixed in #1341

**Pull request closed without merging**
