### PR TITLE
Move from bcc to libbpf

### LINKED ISSUE #1874: Require libbpf
libbpf is easy to build and package. By requiring it we can remove some build time conditionals and keep stuff simpler.

Vendoring it might be an option too although I'm not sure we will benefit from that

### LINKED ISSUE #2173: Linking both latest libbcc_bpf + libbpf library causes segfaults in bpftrace
### What reproduces the bug?
Linking  both latest libbcc_bpf + libbpf library causes segfaults in bpftrace

### bpftrace --info
Segfaults

* Built the bpftrace with latest libbpf + latest libbcc_bpf 
* ldd ./src/bpftrace  | grep bpf
   libbpf.so.0 => /lib64/libbpf.so.0 (0x00007fdd69e99000)
   libbcc_bpf.so.0 => /lib64/libbcc_bpf.so.0 (0x00007fdd69c86000)
* Dynamic loader seems to select the bpf_prog_load_deprecated instead of bpf_prog_load_v0_6_0.
* readelf -Ws libbpf.so.0.8.0 | grep bpf_prog_load
   157: 00000000000298e0    84 FUNC    GLOBAL DEFAULT   13 bpf_prog_load_deprecated@@LIBBPF_0.6.0
   431: 00000000000296f0   485 FUNC    GLOBAL DEFAULT   13 bpf_prog_load_xattr@@LIBBPF_0.0.1
   432: 00000000000298e0    84 FUNC    GLOBAL DEFAULT   13 bpf_prog_load@LIBBPF_0.0.1
   433: 000000000000b800  2369 FUNC    GLOBAL DEFAULT   13 bpf_prog_load@@LIBBPF_0.6.0
   126: 00000000000296f0   485 FUNC    LOCAL  DEFAULT   13 bpf_prog_load_xattr2
   359: 000000000000b800  2369 FUNC    LOCAL  DEFAULT   13 bpf_prog_load_v0_6_0
   543: 00000000000296f0   485 FUNC    GLOBAL DEFAULT   13 bpf_prog_load_xattr
   588: 00000000000298e0    84 FUNC    GLOBAL DEFAULT   13 bpf_prog_load@LIBBPF_0.0.1
   652: 00000000000298e0    84 FUNC    GLOBAL DEFAULT   13 bpf_prog_load_deprecated
   769: 000000000000b800  2369 FUNC    GLOBAL DEFAULT   13 bpf_prog_load@@LIBBPF_0.6.0
   
* readelf -Ws libbcc_bpf.so.0.24.0 | grep bpf_prog_load
  1213: 0000000000125769   626 FUNC    GLOBAL DEFAULT   12 bpf_prog_load_xattr
  1813: 00000000000f756d  1948 FUNC    GLOBAL DEFAULT   12 bpf_prog_load
  5393: 00000000000f756d  1948 FUNC    GLOBAL DEFAULT   12 bpf_prog_load_v0_6_0
  5849: 00000000001259db   106 FUNC    GLOBAL DEFAULT   12 bpf_prog_load_deprecated
    17: 00000000000f3187   670 FUNC    LOCAL  DEFAULT   12 libbpf_bpf_prog_load
    44: 00000000000f69db    74 FUNC    LOCAL  DEFAULT   12 sys_bpf_prog_load
   582: 0000000000125769   626 FUNC    LOCAL  DEFAULT   12 bpf_prog_load_xattr2
  1062: 00000000000f756d  1948 FUNC    GLOBAL DEFAULT   12 bpf_prog_load
  2454: 0000000000125769   626 FUNC    GLOBAL DEFAULT   12 bpf_prog_load_xattr
  3217: 00000000001259db   106 FUNC    GLOBAL DEFAULT   12 bpf_prog_load_deprecated
  3429: 00000000000f756d  1948 FUNC    GLOBAL DEFAULT   12 bpf_prog_load_v0_6_0
 
* The following fixes the problem - libbpf conflicts and btf_dump__new compilation errors:
```
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index 47a050e2..83f79fda 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -125,7 +125,7 @@ target_link_libraries(libbpftrace parser resources runtime aot ast arch cxxdeman
 
 if (LIBBPF_BTF_DUMP_FOUND)
   target_include_directories(runtime PUBLIC ${LIBBPF_INCLUDE_DIRS})
-  target_link_libraries(runtime ${LIBBPF_LIBRARIES})
+  target_link_libraries(runtime ${LIBBCC_BPF_LIBRARIES})
 endif(LIBBPF_BTF_DUMP_FOUND)
 
 if(HAVE_BFD_DISASM)
diff --git a/src/btf.cpp b/src/btf.cpp
index 7d83cf68..a26f7a48 100644
--- a/src/btf.cpp
+++ b/src/btf.cpp
@@ -225,7 +225,7 @@ std::string BTF::c_def(const std::unordered_set<std::string> &set) const
   char err_buf[256];
   int err;
 
-  dump = btf_dump__new(btf, nullptr, &opts, dump_printf);
+  dump = btf_dump__new_deprecated(btf, nullptr, &opts, dump_printf);
   err = libbpf_get_error(dump);
   if (err)
   {
@@ -496,7 +496,7 @@ std::unique_ptr<std::istream> BTF::get_all_funcs() const
   char err_buf[256];
   int err;
 
-  dump = btf_dump__new(btf, nullptr, &opts, dump_printf);
+  dump = btf_dump__new_deprecated(btf, nullptr, &opts, dump_printf);
   err = libbpf_get_error(dump);
   if (err)
   {
@@ -554,7 +554,7 @@ std::map<std::string, std::vector<std::string>> BTF::get_params(
   char err_buf[256];
   int err;
 
-  dump = btf_dump__new(btf, nullptr, &opts, dump_printf);
+  dump = btf_dump__new_deprecated(btf, nullptr, &opts, dump_printf);
   err = libbpf_get_error(dump);
   if (err)
   {
@@ -648,7 +648,7 @@ std::set<std::string> BTF::get_all_structs() const
   char err_buf[256];
   int err;
 
-  dump = btf_dump__new(btf, nullptr, &opts, dump_printf);
+  dump = btf_dump__new_deprecated(btf, nullptr, &opts, dump_printf);
   err = libbpf_get_error(dump);
   if (err)
   {
```
```
Dump of bpftrace:
#3  0x00007ffff7f86bd2 in bpf_object_open (opts=0x7fffffff9310, obj_buf_sz=0, obj_buf=0x0,
    path=0x2 <error: Cannot access memory at address 0x2>) at libbpf.c:6993
#4  __bpf_object__open_xattr (attr=attr@entry=0x7fffffff9390, flags=0) at libbpf.c:7083
#5  0x00007ffff7f8d73d in bpf_prog_load_xattr2 (attr=attr@entry=0x7fffffff93e0, 
    pobj=pobj@entry=0x755738, prog_fd=prog_fd@entry=0x7fffffff97a0) at libbpf.c:9586
#6  0x00007ffff7f8d929 in bpf_prog_load_deprecated (					<--- Used the deprecated API from libbpf instead of bpf_prog_load with 6 parameters
    file=0x2 <error: Cannot access memory at address 0x2>, type=BPF_PROG_TYPE_UNSPEC, 
    pobj=0x755738, prog_fd=0x7fffffff97a0) at libbpf.c:9653
#7  0x00007ffff7e44423 in libbpf_bpf_prog_load (load_attr=0x7fffffff9680, 
    log_buf=0x7fffffff97b0 "", log_buf_sz=4096) at /mnt/bcc/src/cc/libbpf.c:673
#8  0x00007ffff7e4485a in bcc_prog_load_xattr (attr=0x7fffffff9680, prog_len=16, 
    log_buf=0x7fffffff97b0 "", log_buf_size=4096, allow_rlimit=true)
    at /mnt/bcc/src/cc/libbpf.c:759
#9  0x00007ffff7e44c72 in bcc_prog_load (prog_type=BPF_PROG_TYPE_KPROBE, name=0x0, 
    insns=0x7fffffff97a0, prog_len=16, license=0x755738 "GPL", kern_version=331776, 
    log_level=1, log_buf=0x7fffffff97b0 "", log_buf_size=4096)
    at /mnt/bcc/src/cc/libbpf.c:881
#10 0x00000000004e644c in bpftrace::try_load (name=0x0, 
    prog_type=libbpf::BPF_PROG_TYPE_KPROBE, insns=0x7fffffff97a0, insns_cnt=2, loglevel=1, 
    logbuf=0x7fffffff97b0 "", logbuf_size=4096) at /mnt/bpftrace/src/bpffeature.cpp:46
#11 0x00000000004e6746 in bpftrace::BPFfeature::detect_helper (this=0x7fffffffabb0, 
    func_id=libbpf::BPF_FUNC_probe_read, prog_type=libbpf::BPF_PROG_TYPE_KPROBE)
    at /mnt/bpftrace/src/bpffeature.cpp:118
```   

   

**Question :**
* Why do we have to link both libbpf library and libbcc_bpf (which is submodule of libbpf itself) to bpftrace?. These details would be helpful to debug further.

Thanks

--
Sumanth

### PR DESCRIPTION
**Pull request by viktormalik**
This features a number of changes related to using bcc and libbpf.

The main goal is to get rid of the situation where libbpf is linked (and used) twice, possibly in different versions:
```
bpftrace --> libbcc_bpf --> libbpf
bpftrace --> libbpf
```
which confuses the dynamic linker and causes bugs such as #2173.

This is now resolved by not using any bcc function which would further call libbpf. These include especially functions for program loading and map creation. Now, there are only two features used from `bcc/libbpf.h`:
- probe attachment which shouldn't be calling anything from libbpf (except for kfunc, those are handled purely by libbpf)
- definitions of BPF instructions (used in feature detection)

Besides these, bpftrace still uses bcc for:
- USDT probes handling
- ELF/symbols parsing
- library path resolution

Since program loading now depends on libbpf, it is required, which resolves #1874.

This PR also cleans up vendoring of libbpf enums - vendored definitions are used everywhere in bpftrace.

There are some changes to the CI, too. Since the used Ubuntu 20.04 doesn't package libbpf, it is installed from source. Individual runs can specify libbpf version, most of them use the current latest (0.8.0) and there's one case added for an older version (0.5.0) to test some code paths.

Fixes #2173.

##### Checklist

- [ ] Language changes are updated in `man/adoc/bpftrace.adoc` and if needed in `docs/reference_guide.md`
- [x] User-visible and non-trivial changes updated in `CHANGELOG.md`
- [x] The new behaviour is covered by tests

### CODE REVIEW

**Comment by viktormalik** [comment]
The remaining LGTM alert is not related to this PR, it just showed now b/c libbpf and BTF are newly available inside the LGTM environment.

**Comment by fbs** [comment]
+1 but wonder if we should do anything special release wise as its a big change. I'm find with just merging it as we just did a release

**Comment by viktormalik** [comment]
> +1 but wonder if we should do anything special release wise as its a big change. I'm find with just merging it as we just did a release

Agreed. And since it's a big change, it'll be useful to leave it unreleased for some time, to discover more potential bugs.

**Review by fbs — APPROVED** [review]

**Comment by fbs** [comment]
Agree lets just merge it

**Pull request merged**
