### PR TITLE
Link against system installed bcc

### PR DESCRIPTION
**Pull request by danobi**
Previously, bpftrace was cloning bcc from github at build time, building
a version of bcc, then linking against the built bcc. This is a no-go
for many packaging systems including Fedora, openSUSE, and the internal
Facebook one.

This patch requires bcc and bcc development headers be installed to
build bpftrace and removes the build time downloading behavior.

Please see each individual commit for more relevant notes and test plans.

Thanks @caringi for the initial work in #227.

### CODE REVIEW

**Comment by brendangregg** [comment]
This makes a 6x improvement to my build time: from 128 seconds to 21 seconds. Thanks! I'm inclined to merge unless there's a reason not to. @ajor?

**Comment by brendangregg** [comment]
Here's a system without bcc installed:

```
# cmake -DCMAKE_BUILD_TYPE=DEBUG ..
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find LibBcc (missing: LIBBCC_LIBRARIES LIBBCC_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindLibBcc.cmake:42 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:33 (find_package)


-- Configuring incomplete, errors occurred!
See also "/mnt/src/bpftrace-danobi/build/CMakeFiles/CMakeOutput.log".
```

Can that error message be improved? "please install libbcc".

Also, is there still a way to do a download-bcc build? Just curious.

**Comment by bobrik** [comment]
Where does one get `bcc-dev` package on Ubuntu? I don't see any here:

* https://repo.iovisor.org/apt/xenial/pool/main/b/bcc/

When I build the latest bcc, I only get the following:

```
# ls -l pkg
total 16416
-rw-r--r-- 1 root root   280708 Jan 11 20:07 bcc-lua_0.7.0-2_all.deb
-rw-r--r-- 1 root root   344428 Jan 11 20:07 bcc-tools_0.7.0-2_all.deb
-rw-r--r-- 1 root root   274514 Jan 11 20:07 libbcc-examples_0.7.0-2_amd64.deb
-rw-r--r-- 1 root root 15239400 Jan 11 20:07 libbcc_0.7.0-2_all.deb
-rw-r--r-- 1 root root    25858 Jan 11 20:06 python-bcc_0.7.0-2_all.deb
-rw-r--r-- 1 root root    25934 Jan 11 20:06 python3-bcc_0.7.0-2_all.deb
```

There is no mention of that package here as well:

* https://github.com/iovisor/bcc/blob/aaca976c58/debian/control

I can still compile `bpftrace`, because all needed files are in `libbcc`:

```
# dpkg -L libbcc
...
/usr/include/bcc/libbpf.h
...
/usr/lib/x86_64-linux-gnu/libbcc.so
/usr/lib/x86_64-linux-gnu/libbcc.so.0
```

This also breaks on static build earlier, because `libbcc.a` is not packaged. I think this needs fixing in `bcc` and instructions need to be adjusted in `bpftrace` repo.

**Comment by danobi** [comment]
@bobrik I'm afraid I don't have an ubuntu setup handy. Probably why I messed up the instructions :(. I think libbcc is the correct package. I'll correct the docs.

I'll look into the static build as well. I'll file a separate issue for that.

**Comment by danobi** [comment]
#335 has doc fix

**Comment by xbe** [comment]
This breaks docker builds.

```
$ ./build.sh
~/iovisor_bpftrace/bpftrace/docker ~/iovisor_bpftrace/bpftrace
Sending build context to Docker daemon  7.168kB
Step 1/7 : FROM alpine:3.8
 ---> 3f53bb00af94
Step 2/7 : RUN apk add --update   bison   build-base   clang-dev   clang-static   cmake   elfutils-dev   flex-dev   git   linux-headers   llvm5-dev   llvm5-static   zlib-dev   bcc-dev
 ---> Running in 187fb2514dc5
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  bcc-dev (missing):
    required by: world[bcc-dev]
The command '/bin/sh -c apk add --update   bison   build-base   clang-dev   clang-static   cmake   elfutils-dev   flex-dev   git   linux-headers   llvm5-dev   llvm5-static   zlib-dev   bcc-dev' returned a non-zero code: 1
```
Here's the request for BCC in alpine: [alpine#6426](https://bugs.alpinelinux.org/issues/6426).

**Pull request merged**
