### PR TITLE
Fix wrong package name in build instructions

### PR DESCRIPTION
**Pull request by danobi**

### CODE REVIEW

**Comment by danobi** [comment]
> Can you add a fix for the cmake error message too for this? It should say you need to install either libbpfcc or libbcc (old package name).

Do you think it'd make sense to keep it generic in the error message? For example, I use fedora (requirement at work) and the bcc package is called `bcc-devel`.

**Comment by brendangregg** [comment]
I'd make the error message have some human readable text that's generic, followed by package names as examples. Eg:

"Please install the bcc library package, which is required. Depending on your distro, it may be called bpfcclib or bcclib (Ubuntu), bcc-devel (Fedora), or something else. If unavailable, install bcc from source (github.com/iovisor/bcc)."

**Comment by jgallag88** [comment]
Building on Ubuntu is still failing for me, even with these updated instructions. I can install `libbpfcc-dev`, but compilation fails with
```
In file included from /home/ubuntu/bpftrace/src/ast/codegen_llvm.h:8:0,
                 from /home/ubuntu/bpftrace/src/ast/codegen_llvm.cpp:2:
/home/ubuntu/bpftrace/src/ast/irbuilderbpf.h:5:10: fatal error: bcc_usdt.h: No such file or directory
 #include "bcc_usdt.h"
          ^~~~~~~~~~~~
compilation terminated.
src/ast/CMakeFiles/ast.dir/build.make:86: recipe for target 'src/ast/CMakeFiles/ast.dir/codegen_llvm.cpp.o' failed
make[2]: *** [src/ast/CMakeFiles/ast.dir/codegen_llvm.cpp.o] Error 1
CMakeFiles/Makefile2:178: recipe for target 'src/ast/CMakeFiles/ast.dir/all' failed
make[1]: *** [src/ast/CMakeFiles/ast.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```
If I install bcc from source, bpftrace builds and runs correctly.

**Comment by brendangregg** [comment]
This rings a bell -- I added bcc_usdt.h in July 2018

https://github.com/iovisor/bcc/commit/5148fcec9eb93d29949b04ccdfe9b6e6edc6362d

is that ubuntu package an older bcc version?

**Comment by danobi** [comment]
According to the package page, Ubuntu 18.04 is on bcc 0.5.0-5, which was [tagged Nov 2017](https://github.com/iovisor/bcc/releases/tag/v0.5.0)

**Comment by danobi** [comment]
I've gone ahead and updated the instructions with the known issues in this PR. Are we good to merge now?

**Comment by brendangregg** [comment]
Thanks!

**Pull request merged**
